# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='product_code',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
