# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20161011_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='box_quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
