class StateCode:

    STATE_CODES = {
        'alaska': 'AK',
        'alabama': 'AL',
        'arkensas': 'AR',
        'american samoa': 'AS',
        'arizona': 'AZ',
        'california': 'CA',
        'colorado': 'CO',
        'conneticut': 'CT',
        'district of columbia': 'DC',
        'columbia': 'DC',
        'washington dc': 'DC',
        'dc': 'DC',
        'delaware': 'DE',
        'federated states of micronesia': 'FM',
        'miconesia': 'FM',
        'florida': 'FL',
        'georgia': 'GA',
        'guam': 'GU',
        'hawaii': 'HI',
        'iowa': 'IA',
        'indiana': 'IN',
        'idaho': 'ID',
        'illinois': 'IN',
        'kansas': 'KS',
        'kentucky': 'KY',
        'louisianna': 'LA',
        'massachusetts': 'MA',
        'maryland': 'MD',
        'maine': 'ME',
        'marshall islands': 'MH',
        'michigan': 'MI',
        'minnesota': 'MN',
        'missouri': 'MO',
        'northern amriana islands': 'MP',
        'mississippi': 'MS',
        'montana': 'MT',
        'north carolina': 'NC',
        'north dakota': 'ND',
        'nebraska': 'NE',
        'new hampshire': 'NH',
        'new jersey': 'NJ',
        'new mexcio': 'NM',
        'nevada': 'NV',
        'new york': 'NY',
        'ohio': 'OH',
        'oklahoma': 'OK',
        'oregon': 'OR',
        'pennsylvania': 'PA',
        'puerto rico': 'PR',
        'palau': 'PW',
        'rhode island': 'RI',
        'south carolina': 'SC',
        'south dakota': 'SD',
        'tennessee': 'TN',
        'texas': 'TX',
        'utah': 'UT',
        'virginia': 'VA',
        'virgin islands': 'VI',
        'vermont': 'VT',
        'washington': 'WA',
        'wisonsin': 'WI',
        'west virginia': 'WV',
        'wyoming': 'WY',
        'alberta': 'AB',
        'british colombia': 'BC',
        'british columbia': 'BC',
        'manitoba': 'MB',
        'new brunswick': 'NB',
        'newfoundland': 'NF',
        'nova scotia': 'NS',
        'northwest territories': 'NT',
        'ontario': 'ON',
        'prince edward island': 'PE',
        'quebec': 'QC',
        'saskatchewan': 'SK',
        'yukon': 'YT',
        'new south wales': 'NSW',
        'australian capital territory': 'ACT',
        'victoria': 'VIC',
        'queensland': 'QLD',
        'south australia': 'SA',
        'western australia': 'WA',
        'tasmania': 'TAS',
        'northern territory': 'NT',
    }

    def __new__(cls, state_name):
        if not state_name:
            return ''
        if state_name.strip().lower() in cls.STATE_CODES:
            return cls.STATE_CODES[state_name.strip().lower()]
        if len(state_name) < 4:
            return state_name.upper()
        return state_name
