# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SizeChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SizeChartSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('uk_size', models.CharField(max_length=200, verbose_name='UK Size')),
                ('eu_size', models.CharField(max_length=200, verbose_name='EUR Size')),
                ('us_size', models.CharField(max_length=200, verbose_name='USA Size')),
                ('au_size', models.CharField(max_length=200, verbose_name='AUS Size')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labelmaker.SizeChart')),
            ],
            options={
                'ordering': ('sort',),
            },
        ),
    ]
