# Generated by Django 4.2.4 on 2023-08-15 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0003_productimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="SizeChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "verbose_name": "Size Chart",
                "verbose_name_plural": "Size Charts",
            },
        ),
        migrations.CreateModel(
            name="SizeChartSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort", models.PositiveSmallIntegerField(default=0)),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                ("uk_size", models.CharField(max_length=200, verbose_name="UK Size")),
                ("eu_size", models.CharField(max_length=200, verbose_name="EUR Size")),
                ("us_size", models.CharField(max_length=200, verbose_name="USA Size")),
                ("au_size", models.CharField(max_length=200, verbose_name="AUS Size")),
                (
                    "size_chart",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labelmaker.sizechart",
                    ),
                ),
            ],
            options={
                "ordering": ("sort",),
                "verbose_name": "Size Chart Size",
                "verbose_name_plural": "Size Chart Sizes",
            },
        ),
    ]
