# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labelmaker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sizechartsize',
            old_name='supplier',
            new_name='size_chart',
        ),
    ]
