# Generated by Django 2.0.5 on 2018-05-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labelmaker', '0002_auto_20161013_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizechart',
            options={'ordering': ('name',), 'verbose_name': 'Size Chart', 'verbose_name_plural': 'Size Charts'},
        ),
        migrations.AlterModelOptions(
            name='sizechartsize',
            options={'ordering': ('sort',), 'verbose_name': 'Size Chart Size', 'verbose_name_plural': 'Size Chart Sizes'},
        ),
    ]
