# Generated by Django 2.2.7 on 2019-11-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("labelmaker", "0002_auto_20191113_1228")]

    operations = [
        migrations.AlterField(
            model_name="sizechart",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.Supplier",
            ),
        )
    ]
