# Generated by Django 3.1.14 on 2022-03-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labelmaker", "0004_auto_20210601_1017"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sizechart",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sizechartsize",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
