# Generated by Django 4.0.3 on 2022-03-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labelmaker", "0005_auto_20220301_1107"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sizechart",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sizechartsize",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
