version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - lukeshiner
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: xlsxwriter
    versions:
    - 1.3.8
