DEBUG = true
ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = ["http://*", "https://*"]

ADMINS = []

EMAIL_HOST = "email.host.com"
EMAIL_HOST_USER = "user@email.host.com"
EMAIL_HOST_PASSWORD = "EMAIL_PASSWORD"
EMAIL_PORT = "587"
EMAIL_USE_TLS = true

DATABASE_HOST = "localhost"
DATABASE_NAME = "stcadmin"
DATABASE_USER = "postgres"
DATABASE_PASSWORD = "postgres"
DATABASE_PORT = "5432"
TEST_DATABASE_NAME = "stcadmin_test"

CELERY_BROKER_URL = "amqp://localhost//"

BUCKET_DOMAIN = "fake_bucket.com"
BUCKET_ACCESS_KEY = "AAAA"
BUCKET_SECRET_KEY = "BBBB"
PRODUCT_IMAGE_BUCKET="product-images-test.stcstores"

SHOPIFY_SHOP_URL = "fake.myshopify.com"
SHOPIFY_API_VERSION = "2021-10"
SHOPIFY_API_PASSWORD = "6948461984649461564646"

LINNAPI_APPLICATION_ID = "FAKE_LINNAPI_APPLICATION_ID"
LINNAPI_APPLICATION_SECRET = "FAKE_LINNAPI_APPLICATION_SECRET"
LINNAPI_APPLICATION_TOKEN = "FAKE_LINNAPI_APPLICAION_TOKEN"

AMAZON_UK_REFRESH_TOKEN = "FAKE_AMAZON_UK_TOKEN"
AMAZON_UK_LWA_APP_ID = "FAKE_AMAZON_UK_APP_ID"
AMAZON_UK_LWA_CLIENT_SECRET = "FAKE_AMAZON_UK_SECRET"

AMAZON_US_REFRESH_TOKEN = "FAKE_AMAZON_US_TOKEN"
AMAZON_US_LWA_APP_ID = "FAKE_AMAZON_US_APP_ID"
AMAZON_US_LWA_CLIENT_SECRET = "FAKE_AMAZON_US_SECRET"
