# Generated by Django 3.0.6 on 2020-05-13 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shipping", "0003_auto_20200218_1150"),
    ]

    operations = [
        migrations.CreateModel(
            name="ITDManifest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("generating", "Generating Manifest File"),
                            ("error", "Error"),
                            ("complete", "Complete"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "manifest_file",
                    models.FileField(null=True, upload_to="itd/manifests/"),
                ),
            ],
            options={
                "verbose_name": "ITD Manifest",
                "verbose_name_plural": "ITD Manifests",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ITDOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=20)),
                ("customer_id", models.CharField(max_length=20)),
                (
                    "manifest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="itd.ITDManifest",
                    ),
                ),
            ],
            options={
                "verbose_name": "ITD Manifest Order",
                "verbose_name_plural": "ITD Manifest Orders",
            },
        ),
        migrations.CreateModel(
            name="ITDProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                ("weight", models.PositiveIntegerField()),
                ("price", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="itd.ITDOrder"
                    ),
                ),
            ],
            options={
                "verbose_name": "ITD Manifest Product",
                "verbose_name_plural": "ITD Manifest Products",
            },
        ),
        migrations.CreateModel(
            name="ITDConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipping_rules", models.ManyToManyField(to="shipping.ShippingRule")),
            ],
            options={"verbose_name": "ITD Configuration"},
        ),
    ]
