# Generated by Django 3.0.6 on 2020-05-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itd", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itdmanifest",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("generating", "Generating Manifest File"),
                    ("error", "Error"),
                    ("no_orders", "No Orders"),
                ],
                default="open",
                max_length=10,
            ),
        ),
    ]
