# Generated by Django 2.0.7 on 2018-08-01 13:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def move_services(apps, schema_editor):
    Order = apps.get_model("spring_manifest", "SpringOrder")
    ManifestService = apps.get_model("spring_manifest", "ManifestService")
    for order in Order.objects.all():
        service, created = ManifestService.objects.get_or_create(code=order.service)
        order.service_link = service
        order.save()


def move_manifest_type(apps, schema_editor):
    SpringManifest = apps.get_model("spring_manifest", "SpringManifest")
    ManifestType = apps.get_model("spring_manifest", "ManifestType")
    for manifest in SpringManifest.objects.all():
        manifest_type, created = ManifestType.objects.get_or_create(
            name=manifest.manifest_type
        )
        manifest.manifest_type_link = manifest_type
        manifest.save()


def rename_spring_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for group in Group.objects.filter(name="spring").all():
        group.name = "manifests"
        group.save()


def revert_rename_spring_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for group in Group.objects.filter(name="manifests").all():
        group.name = "spring"
        group.save()


class Migration(migrations.Migration):

    replaces = [
        ("spring_manifest", "0001_initial"),
        ("spring_manifest", "0002_auto_20171003_1211"),
        ("spring_manifest", "0003_auto_20171009_1034"),
        ("spring_manifest", "0004_manifestedorder"),
        ("spring_manifest", "0005_manifestedorder_manifest_time"),
        ("spring_manifest", "0006_cloudcommercecountryid_format_code"),
        ("spring_manifest", "0007_auto_20171010_1721"),
        ("spring_manifest", "0008_auto_20171016_1459"),
        ("spring_manifest", "0009_auto_20171016_1552"),
        ("spring_manifest", "0010_auto_20171017_1046"),
        ("spring_manifest", "0011_auto_20171018_1410"),
        ("spring_manifest", "0012_springmanifest_manifest_file"),
        ("spring_manifest", "0013_auto_20171019_1527"),
        ("spring_manifest", "0014_auto_20171024_1026"),
        ("spring_manifest", "0015_auto_20171121_1258"),
        ("spring_manifest", "0016_auto_20171121_1345"),
        ("spring_manifest", "0017_auto_20171128_1025"),
        ("spring_manifest", "0018_auto_20171128_1540"),
        ("spring_manifest", "0019_cloudcommercecountryid_currency_code"),
        ("spring_manifest", "0020_auto_20171204_1343"),
        ("spring_manifest", "0021_springmanifest_status"),
        ("spring_manifest", "0022_auto_20171213_1112"),
        ("spring_manifest", "0023_springmanifest_messages"),
        ("spring_manifest", "0024_auto_20171213_1127"),
        ("spring_manifest", "0025_auto_20180122_1413"),
        ("spring_manifest", "0026_auto_20180418_1028"),
        ("spring_manifest", "0027_auto_20180418_1032"),
        ("spring_manifest", "0028_securedmaildestination_manifest_row_number"),
        ("spring_manifest", "0029_springmanifest_item_advice_file"),
        ("spring_manifest", "0030_springmanifest_docket_file"),
        ("spring_manifest", "0031_counter"),
        ("spring_manifest", "0032_auto_20180423_1500"),
        ("spring_manifest", "0033_auto_20180514_0933"),
        (
            "spring_manifest",
            "0034_cloudcommerceshippingrule_service_squashed_0041_manifestservice_enabled",
        ),
        ("spring_manifest", "0035_springorder_service_link"),
        ("spring_manifest", "0036_move_services"),
        ("spring_manifest", "0037_remove_springorder_service"),
        ("spring_manifest", "0038_auto_20180726_1200"),
        ("spring_manifest", "0039_manifesttype"),
        ("spring_manifest", "0040_springmanifest_manifest_type_link"),
        ("spring_manifest", "0041_move_manifest_type"),
        ("spring_manifest", "0042_manifestservice_manifest_type"),
        ("spring_manifest", "0043_remove_springmanifest_manifest_type"),
        ("spring_manifest", "0044_auto_20180726_1322"),
        ("spring_manifest", "0045_rename_spring_item"),
        ("spring_manifest", "0046_change_manifest_item_meta"),
        ("spring_manifest", "0047_rename_spring_package"),
        ("spring_manifest", "0048_change_manifest_item_meta"),
        ("spring_manifest", "0049_rename_spring_order"),
        ("spring_manifest", "0050_change_manifest_order_meta"),
        ("spring_manifest", "0051_rename_spring_manifest"),
        ("spring_manifest", "0052_change_manifest_meta"),
        (
            "spring_manifest",
            "0053_remove_cloudcommercecountryid_valid_spring_destination",
        ),
        ("spring_manifest", "0054_remove_destination_zone"),
        ("spring_manifest", "0055_rename_spring_group"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CloudCommerceCountryID",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("cc_id", models.IntegerField()),
                ("iso_code", models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DestinationZone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=3)),
                (
                    "format_code",
                    models.CharField(blank=True, default=None, max_length=1, null=True),
                ),
            ],
            options={
                "ordering": ("name",),
                "verbose_name": "Destination Zone",
                "verbose_name_plural": "Destination Zones",
            },
        ),
        migrations.AddField(
            model_name="cloudcommercecountryid",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="spring_manifest.DestinationZone",
            ),
        ),
        migrations.AlterModelOptions(
            name="cloudcommercecountryid", options={"ordering": ("name",)}
        ),
        migrations.AddField(
            model_name="cloudcommercecountryid",
            name="valid_spring_destination",
            field=models.BooleanField(
                default=True, verbose_name="Valid Spring Destination"
            ),
        ),
        migrations.AlterField(
            model_name="cloudcommercecountryid",
            name="iso_code",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="ISO Code"
            ),
        ),
        migrations.CreateModel(
            name="SpringManifest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_manifested",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpringOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=10, unique=True)),
                ("customer_name", models.CharField(max_length=100)),
                ("date_recieved", models.DateTimeField()),
                ("dispatch_date", models.DateTimeField()),
                (
                    "manifest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spring_manifest.SpringManifest",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("PAR", "Spring Parcel"),
                            ("PAK", "Spring Packet"),
                            ("PAT", "Spring Tracked"),
                            ("PAP", "Spring Signed"),
                            ("SMIU", "Secure Mail International Untracked"),
                            ("SMIT", "Secure Mail International Tracked"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spring_manifest.CloudCommerceCountryID",
                    ),
                ),
                ("canceled", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Spring Order",
                "verbose_name_plural": "Spring Orders",
            },
        ),
        migrations.RenameField(
            model_name="springmanifest",
            old_name="time_manifested",
            new_name="time_created",
        ),
        migrations.AddField(
            model_name="springmanifest",
            name="manifest_type",
            field=models.CharField(
                choices=[("T", "Tracked"), ("U", "Untracked")],
                default="U",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="springmanifest",
            name="time_filed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="springmanifest",
            name="manifest_file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterModelOptions(
            name="springmanifest",
            options={"ordering": ["-time_filed", "-time_created"]},
        ),
        migrations.AlterField(
            model_name="springmanifest",
            name="manifest_file",
            field=models.FileField(blank=True, null=True, upload_to="manifests"),
        ),
        migrations.CreateModel(
            name="SpringItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.PositiveIntegerField(default=1)),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SpringPackage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_number", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spring_manifest.SpringOrder",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="springitem",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="spring_manifest.SpringPackage",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="springpackage", unique_together={("package_number", "order")}
        ),
        migrations.AlterField(
            model_name="springitem", name="item_id", field=models.PositiveIntegerField()
        ),
        migrations.AlterField(
            model_name="springpackage",
            name="package_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterModelOptions(
            name="springitem",
            options={
                "ordering": ("item_id",),
                "verbose_name": "Spring Item",
                "verbose_name_plural": "Spring Items",
            },
        ),
        migrations.AlterModelOptions(
            name="springpackage",
            options={
                "ordering": ("package_number",),
                "verbose_name": "Spring Package",
                "verbose_name_plural": "Spring Packages",
            },
        ),
        migrations.AddField(
            model_name="cloudcommercecountryid",
            name="currency_code",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="springmanifest",
            name="status",
            field=models.CharField(
                choices=[
                    ("unfiled", "Unfiled"),
                    ("in_progress", "In Progress"),
                    ("filed", "Filed"),
                    ("failed", "Failed"),
                ],
                default="filed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="springmanifest",
            name="errors",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cloudcommercecountryid",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="spring_manifest.DestinationZone",
            ),
        ),
        migrations.AlterField(
            model_name="springmanifest",
            name="manifest_type",
            field=models.CharField(
                choices=[("T", "Tracked"), ("U", "Untracked"), ("S", "Secure Mail")],
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="SecuredMailDestination",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("manifest_row_number", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Secured Mail Destination",
                "verbose_name_plural": "Secured Mail Destinations",
            },
        ),
        migrations.AddField(
            model_name="cloudcommercecountryid",
            name="secured_mail_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="spring_manifest.SecuredMailDestination",
            ),
        ),
        migrations.AddField(
            model_name="springmanifest",
            name="item_advice_file",
            field=models.FileField(blank=True, null=True, upload_to="item_advice"),
        ),
        migrations.AddField(
            model_name="springmanifest",
            name="docket_file",
            field=models.FileField(blank=True, null=True, upload_to="docket"),
        ),
        migrations.CreateModel(
            name="Counter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("count", models.PositiveIntegerField()),
            ],
            options={"verbose_name": "Counter", "verbose_name_plural": "Counters"},
        ),
        migrations.AlterModelOptions(
            name="cloudcommercecountryid",
            options={
                "ordering": ("name",),
                "verbose_name": "Cloud Commerce Country ID",
                "verbose_name_plural": "Cloud Commerce Country IDs",
            },
        ),
        migrations.AlterModelOptions(
            name="springmanifest",
            options={
                "ordering": ["-time_filed", "-time_created"],
                "verbose_name": "Spring Manifest",
                "verbose_name_plural": "Spring Manifests",
            },
        ),
        migrations.CreateModel(
            name="CloudCommerceShippingRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                ("rule_id", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Cloud Commerce Shipping Rule",
                "verbose_name_plural": "Cloud Commerce Shipping Rules",
            },
        ),
        migrations.CreateModel(
            name="SecuredMailService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "docket_service",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("format", models.CharField(max_length=255)),
                (
                    "proof_of_delivery",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("on_docket", models.BooleanField(default=False)),
                ("on_item_advice", models.BooleanField(default=False)),
                ("on_manifest", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Secured Mail Service",
                "verbose_name_plural": "Secured Mail Services",
            },
        ),
        migrations.CreateModel(
            name="ManifestService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=10)),
                (
                    "shipping_rules",
                    models.ManyToManyField(
                        blank=True, to="spring_manifest.CloudCommerceShippingRule"
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Manifest Service",
                "verbose_name_plural": "Manifest Services",
            },
        ),
        migrations.AddField(
            model_name="securedmailservice",
            name="shipping_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="spring_manifest.ManifestService",
            ),
        ),
        migrations.AddField(
            model_name="springorder",
            name="service_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="spring_manifest.ManifestService",
            ),
        ),
        migrations.RunPython(move_services),
        migrations.RemoveField(model_name="springorder", name="service"),
        migrations.RenameField(
            model_name="springorder", old_name="service_link", new_name="service"
        ),
        migrations.CreateModel(
            name="ManifestType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Manifest Type",
                "verbose_name_plural": "Manifest Types",
            },
        ),
        migrations.AddField(
            model_name="springmanifest",
            name="manifest_type_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="spring_manifest.ManifestType",
            ),
        ),
        migrations.RunPython(move_manifest_type),
        migrations.AddField(
            model_name="manifestservice",
            name="manifest_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="spring_manifest.ManifestType",
            ),
        ),
        migrations.RemoveField(model_name="springmanifest", name="manifest_type"),
        migrations.RenameField(
            model_name="springmanifest",
            old_name="manifest_type_link",
            new_name="manifest_type",
        ),
        migrations.RenameModel(old_name="SpringItem", new_name="ManifestItem"),
        migrations.AlterModelOptions(
            name="manifestitem",
            options={
                "ordering": ("item_id",),
                "verbose_name": "Manifest Item",
                "verbose_name_plural": "Manifest Items",
            },
        ),
        migrations.RenameModel(old_name="SpringPackage", new_name="ManifestPackage"),
        migrations.AlterModelOptions(
            name="manifestpackage",
            options={
                "ordering": ("package_number",),
                "verbose_name": "Manifest Package",
                "verbose_name_plural": "Manifest Packages",
            },
        ),
        migrations.RenameModel(old_name="SpringOrder", new_name="ManifestOrder"),
        migrations.AlterModelOptions(
            name="manifestorder",
            options={
                "verbose_name": "Manifest Order",
                "verbose_name_plural": "Manifest Orders",
            },
        ),
        migrations.RenameModel(old_name="SpringManifest", new_name="Manifest"),
        migrations.AlterModelOptions(
            name="manifest",
            options={
                "ordering": ["-time_filed", "-time_created"],
                "verbose_name": "Manifest",
                "verbose_name_plural": "Manifests",
            },
        ),
        migrations.RemoveField(
            model_name="cloudcommercecountryid", name="valid_spring_destination"
        ),
        migrations.RemoveField(model_name="cloudcommercecountryid", name="zone"),
        migrations.DeleteModel(name="DestinationZone"),
        migrations.RunPython(rename_spring_group, revert_rename_spring_group),
    ]
