# Generated by Django 2.0.8 on 2018-08-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("spring_manifest", "0002_auto_20180801_1306")]

    operations = [
        migrations.AddField(
            model_name="manifestitem",
            name="weight",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="manifestitem",
            name="full_name",
            field=models.CharField(default="?", max_length=255),
        ),
        migrations.AddField(
            model_name="manifestitem",
            name="name",
            field=models.CharField(default="?", max_length=255),
        ),
    ]
