# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-09 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0002_auto_20171003_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudcommercecountryid',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='destinationzone',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='cloudcommercecountryid',
            name='valid_spring_destination',
            field=models.BooleanField(default=True, verbose_name='Valid Spring Destination'),
        ),
        migrations.AlterField(
            model_name='cloudcommercecountryid',
            name='iso_code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='ISO Code'),
        ),
    ]
