# Generated by Django 2.0.8 on 2018-08-02 14:03

from django.db import migrations


class Migration(migrations.Migration):
    def add_italy(apps, schema_editor):
        SecuredMailDestination = apps.get_model(
            "spring_manifest", "SecuredMailDestination"
        )
        destinations = SecuredMailDestination.objects.filter(
            manifest_row_number__gte=19
        )
        for destination in destinations:
            destination.manifest_row_number += 1
            destination.save()
        SecuredMailDestination.objects.create(name="Italy", manifest_row_number=19)

    dependencies = [("spring_manifest", "0002_auto_20180801_1306")]

    operations = [migrations.RunPython(add_italy)]
