# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-09 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0003_auto_20171009_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10)),
                ('service_code', models.CharField(max_length=3)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spring_manifest.CloudCommerceCountryID')),
            ],
        ),
    ]
