# Generated by Django 2.1 on 2018-08-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("spring_manifest", "0004_manifestitem_weight")]

    operations = [
        migrations.CreateModel(
            name="ManifestUpdate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Manifest Update",
                "verbose_name_plural": "Manifest Updates",
                "ordering": ["-timestamp"],
            },
        )
    ]
