# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-09 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0004_manifestedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestedorder',
            name='manifest_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
