# Generated by Django 2.1 on 2018-08-06 13:20

from django.db import migrations, models
from django.utils import timezone


def add_initial_update(apps, schema_editor):
    """Add a completed manifest update."""
    ManifestUpdate = apps.get_model("spring_manifest", "ManifestUpdate")
    epoch = timezone.datetime(
        year=1970, day=1, month=1, tzinfo=timezone.get_current_timezone()
    )
    ManifestUpdate.objects.create(started=epoch, finished=epoch, status="complete")


class Migration(migrations.Migration):

    dependencies = [("spring_manifest", "0004_manifestitem_weight")]

    operations = [
        migrations.CreateModel(
            name="ManifestUpdate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started", models.DateTimeField(auto_now_add=True)),
                ("finished", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Manifest Update",
                "verbose_name_plural": "Manifest Updates",
                "ordering": ["-started"],
            },
        ),
        migrations.RunPython(add_initial_update),
    ]
