# Generated by Django 2.1 on 2018-08-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("spring_manifest", "0005_manifestupdate")]

    operations = [
        migrations.AlterModelOptions(
            name="manifestupdate",
            options={
                "ordering": ["-started"],
                "verbose_name": "Manifest Update",
                "verbose_name_plural": "Manifest Updates",
            },
        ),
        migrations.RenameField(
            model_name="manifestupdate", old_name="timestamp", new_name="started"
        ),
        migrations.AddField(
            model_name="manifestupdate",
            name="finished",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manifestupdate",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
