# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-16 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0007_auto_20171010_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpringManifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_manifested', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SpringOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('date_recieved', models.DateTimeField()),
                ('dispatch_date', models.DateTimeField()),
                ('manifest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spring_manifest.SpringManifest')),
            ],
        ),
        migrations.RemoveField(
            model_name='manifestedorder',
            name='country',
        ),
        migrations.DeleteModel(
            name='ManifestedOrder',
        ),
    ]
