# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-16 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0008_auto_20171016_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='springorder',
            name='package_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='springorder',
            name='product_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
