# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-17 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0009_auto_20171016_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='springmanifest',
            old_name='time_manifested',
            new_name='time_created',
        ),
        migrations.AddField(
            model_name='springmanifest',
            name='manifest_type',
            field=models.CharField(choices=[('T', 'Tracked'), ('U', 'Untracked')], default='PAK', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='springmanifest',
            name='time_filed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='springorder',
            name='service',
            field=models.CharField(choices=[('Parcel', 'PAR'), ('Packet', 'PAK'), ('PAT', 'Tracked')], default='U', max_length=3),
            preserve_default=False,
        ),
    ]
