# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-18 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0010_auto_20171017_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='springorder',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spring_manifest.CloudCommerceCountryID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='springorder',
            name='service',
            field=models.CharField(choices=[('PAR', 'Parcel'), ('PAK', 'Packet'), ('PAT', 'Tracked')], max_length=3),
        ),
    ]
