# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-19 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0011_auto_20171018_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='springmanifest',
            name='manifest_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
