# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-19 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0012_springmanifest_manifest_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='springmanifest',
            options={'ordering': ['-time_filed', '-time_created']},
        ),
        migrations.AddField(
            model_name='springorder',
            name='canceled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='springmanifest',
            name='manifest_file',
            field=models.FileField(blank=True, null=True, upload_to='manifests'),
        ),
    ]
