# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-24 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0013_auto_20171019_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='springorder',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
