# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0014_auto_20171024_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpringItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveIntegerField(default=1)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpringPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='springorder',
            name='package_count',
        ),
        migrations.RemoveField(
            model_name='springorder',
            name='product_count',
        ),
        migrations.AddField(
            model_name='springpackage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spring_manifest.SpringOrder'),
        ),
        migrations.AddField(
            model_name='springitem',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spring_manifest.SpringPackage'),
        ),
        migrations.AlterUniqueTogether(
            name='springpackage',
            unique_together=set([('package_number', 'order')]),
        ),
    ]
