# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0015_auto_20171121_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='springitem',
            name='item_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='springpackage',
            name='package_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
