# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0016_auto_20171121_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='springorder',
            name='service',
            field=models.CharField(choices=[('PAR', 'Parcel'), ('PAK', 'Packet'), ('PAT', 'Tracked'), ('PAP', 'Signed')], max_length=3),
        ),
    ]
