# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0017_auto_20171128_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='springitem',
            options={'ordering': ('item_id',)},
        ),
        migrations.AlterModelOptions(
            name='springpackage',
            options={'ordering': ('package_number',)},
        ),
    ]
