# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0018_auto_20171128_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudcommercecountryid',
            name='currency_code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
