# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0019_cloudcommercecountryid_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudcommercecountryid',
            name='currency_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
