# Generated by Django 2.0 on 2017-12-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0020_auto_20171204_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='springmanifest',
            name='status',
            field=models.CharField(choices=[('unfiled', 'Unfiled'), ('in_progress', 'In Progress'), ('filed', 'Filed')], default='unfiled', max_length=10),
        ),
    ]
