# Generated by Django 2.0 on 2017-12-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0021_springmanifest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='springmanifest',
            name='status',
            field=models.CharField(choices=[('unfiled', 'Unfiled'), ('in_progress', 'In Progress'), ('filed', 'Filed'), ('failed', 'Failed')], default='filed', max_length=20),
        ),
    ]
