# Generated by Django 2.0 on 2017-12-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0022_auto_20171213_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='springmanifest',
            name='messages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
