# Generated by Django 2.0 on 2018-01-22 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0024_auto_20171213_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudcommercecountryid',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spring_manifest.DestinationZone'),
        ),
    ]
