# Generated by Django 2.0.2 on 2018-04-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0025_auto_20180122_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='springmanifest',
            name='manifest_type',
            field=models.CharField(choices=[('T', 'Tracked'), ('U', 'Untracked'), ('S', 'Secure Mail')], max_length=1),
        ),
        migrations.AlterField(
            model_name='springorder',
            name='service',
            field=models.CharField(choices=[('PAR', 'Spring Parcel'), ('PAK', 'Spring Packet'), ('PAT', 'Spring Tracked'), ('PAP', 'Spring Signed'), ('SMIU', 'Secure Mail International Untracked'), ('SMIT', 'Secure Mail International Tracked')], max_length=3),
        ),
    ]
