# Generated by Django 2.0.2 on 2018-04-18 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0026_auto_20180418_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuredMailDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='cloudcommercecountryid',
            name='secured_mail_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spring_manifest.SecuredMailDestination'),
        ),
    ]
