# Generated by Django 2.0.3 on 2018-04-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0028_securedmaildestination_manifest_row_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='springmanifest',
            name='item_advice_file',
            field=models.FileField(blank=True, null=True, upload_to='item_advice'),
        ),
    ]
