# Generated by Django 2.0.3 on 2018-04-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0029_springmanifest_item_advice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='springmanifest',
            name='docket_file',
            field=models.FileField(blank=True, null=True, upload_to='docket'),
        ),
    ]
