# Generated by Django 2.0.3 on 2018-04-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0031_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='springorder',
            name='service',
            field=models.CharField(choices=[('PAR', 'Spring Parcel'), ('PAK', 'Spring Packet'), ('PAT', 'Spring Tracked'), ('PAP', 'Spring Signed'), ('SMIU', 'Secure Mail International Untracked'), ('SMIT', 'Secure Mail International Tracked')], max_length=50),
        ),
    ]
