# Generated by Django 2.0.5 on 2018-05-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0032_auto_20180423_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudcommercecountryid',
            options={'ordering': ('name',), 'verbose_name': 'Cloud Commerce Country ID', 'verbose_name_plural': 'Cloud Commerce Country IDs'},
        ),
        migrations.AlterModelOptions(
            name='counter',
            options={'verbose_name': 'Counter', 'verbose_name_plural': 'Counters'},
        ),
        migrations.AlterModelOptions(
            name='destinationzone',
            options={'ordering': ('name',), 'verbose_name': 'Destination Zone', 'verbose_name_plural': 'Destination Zones'},
        ),
        migrations.AlterModelOptions(
            name='securedmaildestination',
            options={'verbose_name': 'Secured Mail Destination', 'verbose_name_plural': 'Secured Mail Destinations'},
        ),
        migrations.AlterModelOptions(
            name='springitem',
            options={'ordering': ('item_id',), 'verbose_name': 'Spring Item', 'verbose_name_plural': 'Spring Items'},
        ),
        migrations.AlterModelOptions(
            name='springmanifest',
            options={'ordering': ['-time_filed', '-time_created'], 'verbose_name': 'Spring Manifest', 'verbose_name_plural': 'Spring Manifests'},
        ),
        migrations.AlterModelOptions(
            name='springorder',
            options={'verbose_name': 'Spring Order', 'verbose_name_plural': 'Spring Orders'},
        ),
        migrations.AlterModelOptions(
            name='springpackage',
            options={'ordering': ('package_number',), 'verbose_name': 'Spring Package', 'verbose_name_plural': 'Spring Packages'},
        ),
    ]
