# Generated by Django 2.0.7 on 2018-07-26 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('spring_manifest', '0034_cloudcommerceshippingrule_service'), ('spring_manifest', '0035_auto_20180725_1538'), ('spring_manifest', '0036_auto_20180725_1550'), ('spring_manifest', '0037_auto_20180725_1552'), ('spring_manifest', '0038_auto_20180725_1557'), ('spring_manifest', '0039_auto_20180726_0946'), ('spring_manifest', '0040_auto_20180726_1027'), ('spring_manifest', '0041_manifestservice_enabled')]

    dependencies = [
        ('spring_manifest', '0033_auto_20180514_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudCommerceShippingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('rule_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Cloud Commerce Shipping Rule',
                'verbose_name_plural': 'Cloud Commerce Shipping Rules',
            },
        ),
        migrations.CreateModel(
            name='SecuredMailService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docket_service', models.CharField(blank=True, max_length=255, null=True)),
                ('format', models.CharField(max_length=255)),
                ('proof_of_delivery', models.CharField(blank=True, max_length=255, null=True)),
                ('on_docket', models.BooleanField(default=False)),
                ('on_item_advice', models.BooleanField(default=False)),
                ('on_manifest', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Secured Mail Service',
                'verbose_name_plural': 'Secured Mail Services',
            },
        ),
        migrations.CreateModel(
            name='ManifestService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('shipping_rules', models.ManyToManyField(blank=True, to='spring_manifest.CloudCommerceShippingRule')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Manifest Service',
                'verbose_name_plural': 'Manifest Services',
            },
        ),
        migrations.AddField(
            model_name='securedmailservice',
            name='shipping_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spring_manifest.ManifestService'),
        ),
    ]
