# Generated by Django 2.0.7 on 2018-07-26 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0034_cloudcommerceshippingrule_service_squashed_0041_manifestservice_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='springorder',
            name='service_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spring_manifest.ManifestService'),
        ),
    ]
