# Generated by Django 2.0.7 on 2018-07-26 11:18

from django.db import migrations


def move_services(apps, schema_editor):
    Order = apps.get_model('spring_manifest', 'SpringOrder')
    ManifestService = apps.get_model('spring_manifest', 'ManifestService')
    for order in Order.objects.all():
        service, created = ManifestService.objects.get_or_create(
            code=order.service)
        order.service_link = service
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0035_springorder_service_link'),
    ]

    operations = [
        migrations.RunPython(move_services),
    ]
