# Generated by Django 2.0.7 on 2018-07-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0037_remove_springorder_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='springorder',
            old_name='service_link',
            new_name='service',
        ),
    ]
