# Generated by Django 2.0.7 on 2018-07-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0038_auto_20180726_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Manifest Type',
                'verbose_name_plural': 'Manifest Types',
            },
        ),
    ]
