# Generated by Django 2.0.7 on 2018-07-26 13:08

from django.db import migrations


def move_manifest_type(apps, schema_editor):
    SpringManifest = apps.get_model('spring_manifest', 'SpringManifest')
    ManifestType = apps.get_model('spring_manifest', 'ManifestType')
    for manifest in SpringManifest.objects.all():
        manifest_type, created = ManifestType.objects.get_or_create(
            name=manifest.manifest_type)
        manifest.manifest_type_link = manifest_type
        manifest.save()


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0040_springmanifest_manifest_type_link'),
    ]

    operations = [
        migrations.RunPython(move_manifest_type),
    ]
