# Generated by Django 2.0.7 on 2018-07-26 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0041_move_manifest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestservice',
            name='manifest_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spring_manifest.ManifestType'),
        ),
    ]
