# Generated by Django 2.0.7 on 2018-07-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0042_manifestservice_manifest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='springmanifest',
            name='manifest_type',
        ),
    ]
