# Generated by Django 2.0.7 on 2018-07-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0043_remove_springmanifest_manifest_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='springmanifest',
            old_name='manifest_type_link',
            new_name='manifest_type',
        ),
    ]
