# Generated by Django 2.0.7 on 2018-08-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0044_auto_20180726_1322'),
    ]

    operations = [migrations.RenameModel('SpringItem', 'ManifestItem')]
