# Generated by Django 2.0.7 on 2018-08-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0045_rename_spring_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manifestitem',
            options={'ordering': ('item_id',), 'verbose_name': 'Manifest Item', 'verbose_name_plural': 'Manifest Items'},
        ),
    ]
