# Generated by Django 2.0.7 on 2018-08-01 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0046_change_manifest_item_meta'),
    ]

    operations = [migrations.RenameModel('SpringPackage', 'ManifestPackage')]
