# Generated by Django 2.0.7 on 2018-08-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0047_rename_spring_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manifestpackage',
            options={'ordering': ('package_number',), 'verbose_name': 'Manifest Package', 'verbose_name_plural': 'Manifest Packages'},
        ),
    ]
