# Generated by Django 2.0.7 on 2018-08-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0048_change_manifest_item_meta'),
    ]

    operations = [migrations.RenameModel('SpringOrder', 'ManifestOrder')]
