# Generated by Django 2.0.7 on 2018-08-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0049_rename_spring_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manifestorder',
            options={'verbose_name': 'Manifest Order', 'verbose_name_plural': 'Manifest Orders'},
        ),
    ]
