# Generated by Django 2.0.7 on 2018-08-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0050_change_manifest_order_meta'),
    ]

    operations = [migrations.RenameModel('SpringManifest', 'Manifest')]
