# Generated by Django 2.0.7 on 2018-08-01 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0051_rename_spring_manifest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manifest',
            options={'ordering': ['-time_filed', '-time_created'], 'verbose_name': 'Manifest', 'verbose_name_plural': 'Manifests'},
        ),
    ]
