# Generated by Django 2.0.7 on 2018-08-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0052_change_manifest_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudcommercecountryid',
            name='valid_spring_destination',
        ),
    ]
