# Generated by Django 2.0.7 on 2018-08-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spring_manifest', '0053_remove_cloudcommercecountryid_valid_spring_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudcommercecountryid',
            name='zone',
        ),
        migrations.DeleteModel(
            name='DestinationZone',
        ),
    ]
