"""ProductEditorBase class."""


class ProductEditorBase:
    """Container for constants used by product_editor."""

    VARIATION = "variation"
    SINGLE = "single"
    USED = "used"
    NEW_PRODUCT = "new_product_data"
    TYPE = "type"
    CLEAR_PRODUCT = "clear_product"
    BASIC = "basic_info"
    PRODUCT_INFO = "product_info"
    VARIATION_OPTIONS = "variation_options"
    UNUSED_VARIATIONS = "unused_variations"
    LISTING_OPTIONS = "listing_options"
    VARIATION_INFO = "variation_info"
    VARIATION_LISTING_OPTIONS = "variation_listing_options"
    FINISH = "finish"
    TITLE = "title"
    BARCODE = "barcode"
    DESCRIPTION = "description"
    PRICE = "price"
    VAT_RATE = "vat_rate"
    EX_VAT = "ex_vat"
    DEPARTMENT = "department"
    WAREHOUSE = "warehouse"
    BAYS = "bays"
    PURCHASE_PRICE = "purchase_price"
    RETAIL_PRICE = "retail_price"
    STOCK_LEVEL = "stock_level"
    SUPPLIER = "supplier"
    SUPPLIER_SKU = "supplier_sku"
    WEIGHT = "weight"
    HEIGHT = "height"
    WIDTH = "width"
    LENGTH = "length"
    PACKAGE_TYPE = "package_type"
    BRAND = "brand"
    MANUFACTURER = "manufacturer"
    GENDER = "gender"
    AMAZON_BULLET_POINTS = "amazon_bullet_points"
    AMAZON_SEARCH_TERMS = "amazon_search_terms"
    OPTIONS = "options"
    LOCATION = "location"
    DIMENSIONS = "dimensions"
    HEAVY_AND_LARGE = "Heavy and Large"
    COURIER = "Courier"
    STANDARD = "Standard"
    EXPRESS = "Express"
    INCOMPLETE = "Incomplete"
    RANGE_ID = "range_id"
    PRODUCT_ID = "product_id"
    EXISTING_VARIATIONS = "existing_variations"
