# Generated by Django 3.0 on 2019-12-12 15:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("home", "0002_cloudcommerceuser")]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("image", models.ImageField(upload_to="feedback")),
                ("score", models.IntegerField(default=0)),
            ],
            options={"verbose_name": "Feedback", "verbose_name_plural": "Feedback"},
        ),
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateField(default=django.utils.timezone.now)),
                ("order_id", models.CharField(blank=True, max_length=10, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "feedback_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedback.Feedback",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.CloudCommerceUser",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Feedback",
                "verbose_name_plural": "User Feedback",
            },
        ),
    ]
