# Generated by Django 4.2.3 on 2023-07-18 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0002_auto_20210601_1017"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userfeedback",
            name="feedback_type",
        ),
        migrations.RemoveField(
            model_name="userfeedback",
            name="user",
        ),
        migrations.DeleteModel(
            name="Feedback",
        ),
        migrations.DeleteModel(
            name="UserFeedback",
        ),
    ]
