# Generated by Django 3.0.9 on 2020-08-05 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shipping", "0014_vatrate"),
    ]

    operations = [
        migrations.CreateModel(
            name="FBACountry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postage_price", models.PositiveIntegerField()),
                ("max_weight", models.PositiveIntegerField(blank=True, null=True)),
                ("max_size", models.FloatField(blank=True, null=True)),
                (
                    "dimension_unit",
                    models.CharField(
                        choices=[("inches", "Inches"), ("cm", "Centimeters")],
                        max_length=10,
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(
                        choices=[("lb", "Kilograms"), ("kg", "Pounds")], max_length=2
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fba_countries",
                        to="shipping.Country",
                    ),
                ),
                (
                    "extra_countries",
                    models.ManyToManyField(
                        blank=True,
                        related_name="extra_fba_countries",
                        to="shipping.Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "FBA Country",
                "verbose_name_plural": "FBA Countries",
            },
        ),
        migrations.CreateModel(
            name="FBAOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("product_SKU", models.CharField(max_length=20)),
                ("product_ID", models.CharField(max_length=50)),
                ("product_name", models.CharField(max_length=255)),
                ("selling_price", models.PositiveIntegerField()),
                ("FBA_fee", models.PositiveIntegerField()),
                ("aproximate_quantity", models.PositiveIntegerField()),
                ("quantity_sent", models.PositiveIntegerField(blank=True, null=True)),
                ("box_width", models.PositiveIntegerField(blank=True, null=True)),
                ("box_height", models.PositiveIntegerField(blank=True, null=True)),
                ("box_depth", models.PositiveIntegerField(blank=True, null=True)),
                ("box_weight", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("priority", models.PositiveIntegerField(default=999)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fba.FBACountry"
                    ),
                ),
                (
                    "fullfilled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FBA Order",
                "verbose_name_plural": "FBA Orders",
                "ordering": ["priority"],
            },
        ),
    ]
