# Generated by Django 3.1 on 2020-08-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaorder",
            name="max_quantity",
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
