# Generated by Django 3.1.2 on 2020-10-21 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaregion",
            name="default_country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="fba.fbacountry",
            ),
            preserve_default=False,
        ),
    ]
