# Generated by Django 3.1.2 on 2020-10-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0002_fbaregion_default_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaorder",
            name="printed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fbaorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not Processed", "Not Processed"),
                    ("Awaiting Collection Booking", "Awaiting Collection Booking"),
                    ("Printed", "Printed"),
                    ("Fulfilled", "Fulfilled"),
                ],
                max_length=255,
            ),
        ),
    ]
