# Generated by Django 3.1.1 on 2020-09-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0002_fbaorder_max_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fbaorder",
            name="max_quantity",
        ),
    ]
