# Generated by Django 3.1.1 on 2020-09-14 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0014_vatrate"),
        ("fba", "0003_remove_fbaorder_max_quantity"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FBACountry",
            new_name="FBARegion",
        ),
        migrations.AlterModelOptions(
            name="fbaregion",
            options={
                "verbose_name": "FBA Region",
                "verbose_name_plural": "FBA Regions",
            },
        ),
    ]
