# Generated by Django 3.1.2 on 2020-10-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0003_auto_20201021_1158"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fbaorder",
            name="box_weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
