# Generated by Django 3.1.1 on 2020-09-14 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0014_vatrate"),
        ("fba", "0004_auto_20200914_1224"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fbaregion",
            name="country",
        ),
        migrations.RemoveField(
            model_name="fbaregion",
            name="extra_countries",
        ),
        migrations.AddField(
            model_name="fbaregion",
            name="name",
            field=models.CharField(default="Europe", max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="FBACountry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fba_countries",
                        to="shipping.country",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fba_regions",
                        to="fba.fbaregion",
                    ),
                ),
            ],
        ),
    ]
