# Generated by Django 3.1.2 on 2020-10-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0005_fbaorder_small_and_light"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaorder",
            name="product_hs_code",
            field=models.CharField(default="None", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fbaorder",
            name="product_weight",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
