# Generated by Django 3.1.1 on 2020-09-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0005_auto_20200914_1228"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fbacountry",
            options={
                "verbose_name": "FBA Country",
                "verbose_name_plural": "FBA Countries",
            },
        ),
        migrations.RenameField(
            model_name="fbaorder",
            old_name="country",
            new_name="region",
        ),
    ]
