# Generated by Django 3.1.1 on 2020-10-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0006_auto_20200914_1241"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaregion",
            name="auto_close",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
