# Generated by Django 3.1.2 on 2020-10-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0006_auto_20201021_1452"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fbaorder",
            old_name="fullfilled_by",
            new_name="fulfilled_by",
        ),
    ]
