# Generated by Django 3.1.2 on 2020-10-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0007_fbaregion_auto_close"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not Processed", "Not Processed"),
                    ("Awaiting Collection Booking", "Awaiting Collection Booking"),
                    ("Awaiting Collection Booking", "Awaiting Collection Booking"),
                ],
                default="Not Processed",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
