# Generated by Django 3.1.2 on 2020-10-20 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0014_vatrate"),
        ("fba", "0008_fbaorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaregion",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="shipping.currency",
            ),
            preserve_default=False,
        ),
    ]
