# Generated by Django 3.1.2 on 2020-11-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0009_fbashippingprice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fbaorder",
            name="box_depth",
        ),
        migrations.RemoveField(
            model_name="fbaorder",
            name="box_height",
        ),
        migrations.RemoveField(
            model_name="fbaorder",
            name="box_width",
        ),
        migrations.AlterField(
            model_name="fbaregion",
            name="weight_unit",
            field=models.CharField(
                choices=[("kg", "Kilograms"), ("lb", "Pounds")], max_length=2
            ),
        ),
    ]
