# Generated by Django 3.1.2 on 2020-11-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0009_fbashippingprice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fbaorder",
            name="box_depth",
        ),
        migrations.RemoveField(
            model_name="fbaorder",
            name="box_height",
        ),
        migrations.RemoveField(
            model_name="fbaorder",
            name="box_width",
        ),
    ]
