# Generated by Django 3.1.2 on 2020-11-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0010_auto_20201103_0941"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaorder",
            name="product_asin",
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
