# Generated by Django 3.1.2 on 2020-11-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0011_fbaorder_product_asin"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaorder",
            name="on_hold",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fbaorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not Processed", "Not Processed"),
                    ("Awaiting Collection Booking", "Awaiting Collection Booking"),
                    ("Printed", "Printed"),
                    ("Fulfilled", "Fulfilled"),
                    ("On Hold", "On Hold"),
                ],
                max_length=255,
            ),
        ),
    ]
