# Generated by Django 3.1.3 on 2020-11-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0012_auto_20201103_1355"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaorder",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
