# Generated by Django 3.1.3 on 2020-11-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0013_fbaorder_tracking_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaorder",
            name="product_image_url",
            field=models.URLField(blank=True),
        ),
    ]
