# Generated by Django 3.1.3 on 2020-11-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0014_fbaorder_product_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaorder",
            name="product_supplier",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
