# Generated by Django 3.1.4 on 2020-12-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0016_fbaorder_update_stock_level_when_complete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fbaregion",
            name="dimension_unit",
        ),
        migrations.RemoveField(
            model_name="fbaregion",
            name="flag",
        ),
        migrations.RemoveField(
            model_name="fbaregion",
            name="weight_unit",
        ),
        migrations.AddField(
            model_name="fbaregion",
            name="delivery_unit",
            field=models.CharField(
                choices=[("m", "Metric"), ("i", "Imperial")], default="m", max_length=1
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fbaregion",
            name="fulfillment_unit",
            field=models.CharField(
                choices=[("m", "Metric"), ("i", "Imperial")], default="m", max_length=1
            ),
            preserve_default=False,
        ),
    ]
