# Generated by Django 3.1.4 on 2020-12-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0017_auto_20201202_1342"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fbaregion",
            name="delivery_unit",
        ),
    ]
