# Generated by Django 3.1.4 on 2020-12-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0021_auto_20201215_1011"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaorder",
            name="is_combinable",
            field=models.BooleanField(default=False),
        ),
    ]
