# Generated by Django 3.1.6 on 2021-02-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0024_auto_20210209_1409"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaorder",
            name="is_fragile",
            field=models.BooleanField(default=False),
        ),
    ]
