# Generated by Django 3.1.11 on 2021-05-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0025_fbaorder_is_fragile"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaorder",
            name="product_is_multipack",
            field=models.BooleanField(default=False),
        ),
    ]
