# Generated by Django 3.2.6 on 2021-09-07 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0027_auto_20210601_1017"),
    ]

    operations = [
        migrations.CreateModel(
            name="FBAShipmentDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "recipient_last_name",
                    models.CharField(default="STC FBA", max_length=255),
                ),
                ("address_line_1", models.CharField(max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("address_line_3", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("postcode", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "FBA Shipment Destination",
                "verbose_name_plural": "FBA Shipment Destinations",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="FBAShipmentExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "FBA Shipment Export",
                "verbose_name_plural": "FBA Shipment Exports",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="FBAShipmentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("identifier", models.CharField(max_length=255)),
                ("priority", models.SmallIntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FBA Shipment Method",
                "verbose_name_plural": "FBA Shipment Methods",
                "ordering": ("priority",),
            },
        ),
        migrations.CreateModel(
            name="FBAShipmentOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_on_hold", models.BooleanField(default=False)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fba.fbashipmentdestination",
                    ),
                ),
                (
                    "export",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment_order",
                        to="fba.fbashipmentexport",
                    ),
                ),
                (
                    "shipment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fba.fbashipmentmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "FBA Shipment Order",
                "verbose_name_plural": "FBA Shipment Orders",
            },
        ),
        migrations.CreateModel(
            name="FBAShipmentPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("quantity", models.SmallIntegerField()),
                ("length_cm", models.SmallIntegerField()),
                ("width_cm", models.SmallIntegerField()),
                ("height_cm", models.SmallIntegerField()),
                ("weight_kg", models.FloatField()),
                ("value", models.SmallIntegerField(default=100)),
                (
                    "country_of_origin",
                    models.CharField(default="United Kingdom", max_length=255),
                ),
                ("hr_code", models.CharField(max_length=255)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment_package",
                        to="fba.fbashipmentorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "FBA Shipment Package",
                "verbose_name_plural": "FBA Shipment Packages",
            },
        ),
    ]
