# Generated by Django 3.2.7 on 2021-09-08 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fba",
            "0028_fbashipmentdestination_fbashipmentexport_fbashipmentmethod_fbashipmentorder_fbashipmentpackage",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fbashipmentpackage",
            name="country_of_origin",
        ),
        migrations.RemoveField(
            model_name="fbashipmentpackage",
            name="description",
        ),
        migrations.RemoveField(
            model_name="fbashipmentpackage",
            name="hr_code",
        ),
        migrations.RemoveField(
            model_name="fbashipmentpackage",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="fbashipmentpackage",
            name="sku",
        ),
        migrations.RemoveField(
            model_name="fbashipmentpackage",
            name="value",
        ),
        migrations.RemoveField(
            model_name="fbashipmentpackage",
            name="weight_kg",
        ),
        migrations.CreateModel(
            name="FBAShipmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("quantity", models.SmallIntegerField()),
                ("weight_kg", models.FloatField()),
                ("value", models.SmallIntegerField(default=100)),
                (
                    "country_of_origin",
                    models.CharField(default="United Kingdom", max_length=255),
                ),
                ("hr_code", models.CharField(max_length=255)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment_item",
                        to="fba.fbashipmentpackage",
                    ),
                ),
            ],
            options={
                "verbose_name": "FBA Shipment Item",
                "verbose_name_plural": "FBA Shipment Items",
            },
        ),
    ]
