# Generated by Django 3.2.8 on 2021-10-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0029_auto_20210908_1205"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fbaorder",
            name="fulfillment_center",
        ),
        migrations.DeleteModel(
            name="FulfillmentCenter",
        ),
    ]
