# Generated by Django 3.2.8 on 2021-10-07 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0030_auto_20211007_1144"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fbashipmentpackage",
            old_name="order",
            new_name="shipment_order",
        ),
        migrations.AddField(
            model_name="fbashipmentpackage",
            name="fba_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipment_package",
                to="fba.fbaorder",
            ),
        ),
    ]
