# Generated by Django 4.0.3 on 2022-03-28 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fba', '0031_auto_20211007_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fbaorder',
            name='product_ID',
        ),
        migrations.AlterField(
            model_name='fbaorder',
            name='region',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fba.fbaregion'),
        ),
        migrations.AlterField(
            model_name='fbaorder',
            name='selling_price',
            field=models.PositiveIntegerField(),
        ),
    ]
