# Generated by Django 4.1.2 on 2022-10-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0032_remove_fbaorder_product_id_alter_fbaorder_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaregion",
            name="min_shipping_cost",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fbaregion",
            name="postage_overhead_g",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fbaregion",
            name="postage_per_kg",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="fbaregion",
            name="postage_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
