# Generated by Django 4.1.4 on 2022-12-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fba",
            "0035_rename_recipient_last_name_fbashipmentdestination_recipient_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipmentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name": "Shipment Config",
            },
        ),
    ]
