# Generated by Django 4.1.6 on 2023-02-13 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fba", "0036_shipmentconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="FBATrackingNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_number", models.CharField(max_length=255)),
                (
                    "fba_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_numbers",
                        to="fba.fbaorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "FBA Tracking Number",
                "verbose_name_plural": "FBA Tracking Numbers",
            },
        ),
    ]
