# Generated by Django 4.1.6 on 2023-02-14 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fba", "0037_fbatrackingnumber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fbaorder",
            name="tracking_number",
        ),
    ]
