# Generated by Django 4.2 on 2023-04-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fba", "0039_fbashipmentorder_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fbaorder",
            name="product_asin",
            field=models.CharField(max_length=24),
        ),
    ]
