# Generated by Django 4.2.1 on 2023-05-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fba", "0041_fbaregion_expiry_date_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaorder",
            name="product_barcode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
