# Generated by Django 4.2.4 on 2023-08-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fba", "0042_fbaorder_product_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fbashipmentitem",
            name="country_of_origin",
            field=models.CharField(
                default="United Kingdom",
                max_length=255,
                verbose_name="Country of Origin",
            ),
        ),
        migrations.AlterField(
            model_name="fbashipmentitem",
            name="hr_code",
            field=models.CharField(max_length=255, verbose_name="HR Code"),
        ),
        migrations.AlterField(
            model_name="fbashipmentitem",
            name="sku",
            field=models.CharField(max_length=255, verbose_name="SKU"),
        ),
        migrations.AlterField(
            model_name="fbashipmentitem",
            name="weight_kg",
            field=models.FloatField(verbose_name="Weight (kg)"),
        ),
    ]
