# Generated by Django 4.2.5 on 2023-09-11 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fba", "0044_fbaorder_tmp_fulfilled_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fbaorder",
            name="fulfilled_by",
        ),
    ]
