# Generated by Django 4.2.5 on 2023-09-20 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0023_alter_baseproduct_options_remove_productrange_hidden_and_more",
        ),
        ("fba", "0046_rename_tmp_fulfilled_by_fbaorder_fulfilled_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaorder",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fba_orders",
                to="inventory.baseproduct",
            ),
        ),
    ]
