# Generated by Django 4.2.5 on 2023-09-27 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0024_alter_exchangerate_unique_together"),
        ("fba", "0049_fbaregion_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fbaregion",
            name="default_country",
        ),
        migrations.AlterField(
            model_name="fbaregion",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="shipping.country"
            ),
        ),
    ]
