# Generated by Django 4.2.5 on 2023-09-27 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fba", "0050_remove_fbaregion_default_country_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FBACountry",
        ),
    ]
