# Generated by Django 4.2.5 on 2023-10-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fba", "0051_delete_fbacountry"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaregion",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
