# Generated by Django 4.2.6 on 2023-10-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fba", "0053_remove_fbaorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaorder",
            name="is_stopped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fbaorder",
            name="stopped_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fbaorder",
            name="stopped_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fbaorder",
            name="stopped_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
