# Generated by Django 4.2.6 on 2023-10-26 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("fba", "0054_fbaorder_is_stopped_fbaorder_stopped_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fbaorder",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
