# Generated by Django 5.0.1 on 2024-01-11 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fba", "0056_remove_fbashipmentpackage_fba_order_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FBAShippingPrice",
        ),
    ]
