# Generated by Django 5.0.2 on 2024-02-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0057_delete_fbashippingprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaorder",
            name="priority_temp",
            field=models.BooleanField(default=False),
        ),
    ]
