# Generated by Django 5.0.2 on 2024-02-28 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0059_alter_fbaorder_options_remove_fbaorder_priority"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fbaorder",
            options={
                "ordering": ["-priority"],
                "verbose_name": "FBA Order",
                "verbose_name_plural": "FBA Orders",
            },
        ),
        migrations.RenameField(
            model_name="fbaorder",
            old_name="priority_temp",
            new_name="priority",
        ),
    ]
