# Generated by Django 5.0.3 on 2024-03-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0060_alter_fbaorder_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaregion",
            name="placement_fee",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
