# Generated by Django 5.0.4 on 2024-04-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0062_fbaprofitfile_fbaprofit"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbashipmentorder",
            name="at_risk",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fbashipmentorder",
            name="planned_shipment_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
