# Generated by Django 5.0.6 on 2024-06-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0064_remove_fbaorder_is_fragile"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbaorder",
            name="no_stickers",
            field=models.BooleanField(default=False),
        ),
    ]
