# Generated by Django 5.0.6 on 2024-06-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0065_fbaorder_no_stickers"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParcelhubAPIConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_id", models.CharField(blank=True, max_length=20, null=True)),
                ("customer_id", models.CharField(blank=True, max_length=20, null=True)),
                ("provider_id", models.CharField(blank=True, max_length=20, null=True)),
                ("ready_time", models.TimeField(blank=True, null=True)),
                ("close_time", models.TimeField(blank=True, null=True)),
                (
                    "collection_contact_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "collection_company_name",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "collection_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "collection_address_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "collection_address_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "collection_city",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "collection_area",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "collection_postcode",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "collection_country",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "collection_email",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "verbose_name": "Parcelhub API Config",
            },
        ),
    ]
