# Generated by Django 5.0.7 on 2024-07-15 14:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0066_parcelhubapiconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbashipmentorder",
            name="filing_error",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ParcelhubShipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipment_id", models.CharField(max_length=255)),
                ("courier_tracking_number", models.CharField(max_length=255)),
                ("parcelhub_tracking_number", models.CharField(max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "shipment_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parcelhub_shipment",
                        to="fba.fbashipmentorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcelhub Shipment",
                "verbose_name_plural": "Parcelhub Shipments",
                "ordering": ("-created_at",),
            },
        ),
    ]
