# Generated by Django 5.0.7 on 2024-07-22 13:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0067_fbashipmentorder_filing_error_parcelhubshipment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fbashipmentorder",
            name="filing_error",
        ),
        migrations.CreateModel(
            name="ParcelhubShipmentFiling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "shipment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment_filings",
                        to="fba.parcelhubshipment",
                    ),
                ),
                (
                    "shipment_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parcelhub_shipment_filings",
                        to="fba.fbashipmentorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcelhub Shipment Filing",
                "verbose_name_plural": "Parcelhub Shipment Filings",
                "ordering": ("-started_at",),
            },
        ),
    ]
