# Generated by Django 5.0.7 on 2024-08-05 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fba", "0068_remove_fbashipmentorder_filing_error_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcelhubshipmentfiling",
            name="shipment_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcelhub_shipment_filings",
                to="fba.fbashipmentorder",
            ),
        ),
    ]
