# Generated by Django 4.2.1 on 2023-05-31 12:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0021_remove_baseproduct_latest_stock_change"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reorder_count",
                        to="inventory.baseproduct",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reorder",
                "verbose_name_plural": "Reorders",
            },
        ),
    ]
