# Generated by Django 4.2.4 on 2023-08-02 12:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0022_baseproduct_additional_suppliers"),
        ("restock", "0002_reorder_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="reorder",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reorder",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="reorder",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="reorder",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reorders",
                to="inventory.baseproduct",
                verbose_name="Product",
            ),
        ),
    ]
