# Generated by Django 4.2.3 on 2023-07-25 14:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("home", "0010_alter_staff_options"),
        ("inventory", "0022_baseproduct_additional_suppliers"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("export_date", models.DateField(auto_now_add=True, unique=True)),
                ("report_sent", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Purchase Export",
                "verbose_name_plural": "Purchase Exports",
                "ordering": ("-export_date",),
            },
        ),
        migrations.CreateModel(
            name="PurchaseSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_charge",
                    models.DecimalField(decimal_places=2, max_digits=4, null=True),
                ),
                ("send_report_to", models.EmailField(max_length=254, null=True)),
            ],
            options={
                "verbose_name": "Purchase Settings",
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "time_of_purchase_item_price",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "time_of_purchase_charge",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "export",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="purchases.purchaseexport",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_purchases",
                        to="inventory.baseproduct",
                    ),
                ),
                (
                    "purchased_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="home.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase",
                "verbose_name_plural": "Purchases",
                "ordering": ("-created_at",),
            },
        ),
    ]
