# Generated by Django 4.2.4 on 2023-09-04 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseexport",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
