# Generated by Django 4.2.7 on 2023-11-16 10:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("inventory", "0026_product_is_flammable"),
        ("home", "0011_staff_fba_packer"),
        ("purchases", "0002_purchaseexport_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasePurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "export",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="purchases.purchaseexport",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "purchased_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="home.staff",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="ProductPurchase",
            fields=[
                (
                    "basepurchase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="purchases.basepurchase",
                    ),
                ),
                (
                    "time_of_purchase_item_price",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "time_of_purchase_charge",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_purchases",
                        to="inventory.baseproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase",
                "verbose_name_plural": "Purchases",
                "ordering": ("-created_at",),
            },
            bases=("purchases.basepurchase",),
        ),
        migrations.DeleteModel(
            name="Purchase",
        ),
    ]
