# Generated by Django 3.1.8 on 2021-05-05 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0002_purchase_cancelled"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockpurchase",
            name="discount_percentage",
            field=models.PositiveSmallIntegerField(
                default=25,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
            preserve_default=False,
        ),
    ]
