# Generated by Django 4.2.7 on 2023-11-21 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0024_alter_exchangerate_unique_together"),
        ("purchases", "0003_basepurchase_productpurchase_delete_purchase"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherPurchase",
            fields=[
                (
                    "basepurchase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="purchases.basepurchase",
                    ),
                ),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                "verbose_name": "Other Purchase",
                "verbose_name_plural": "Other Purchases",
                "ordering": ("-created_at",),
            },
            bases=("purchases.basepurchase",),
        ),
        migrations.AlterModelOptions(
            name="productpurchase",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Product Purchase",
                "verbose_name_plural": "Product Purchases",
            },
        ),
        migrations.AlterField(
            model_name="productpurchase",
            name="time_of_purchase_charge",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.CreateModel(
            name="ShippingPurchase",
            fields=[
                (
                    "basepurchase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="purchases.basepurchase",
                    ),
                ),
                ("weight_grams", models.PositiveIntegerField()),
                (
                    "time_of_purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "shipping_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipping_purchases",
                        to="shipping.shippingprice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Purchase",
                "verbose_name_plural": "Shipping Purchases",
                "ordering": ("-created_at",),
            },
            bases=("purchases.basepurchase",),
        ),
        migrations.CreateModel(
            name="PurchasableShippingService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shipping_service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shipping.shippingservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchaseable Shipping Service",
                "verbose_name_plural": "Purchaseable Shipping Services",
            },
        ),
    ]
