# Generated by Django 3.1.8 on 2021-05-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0004_auto_20210511_0956"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="paid",
        ),
    ]
