# Generated by Django 3.1.10 on 2021-05-13 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0005_remove_purchase_paid"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseNote",
            fields=[
                (
                    "purchase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="purchases.purchase",
                    ),
                ),
                ("text", models.TextField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("purchases.purchase",),
        ),
    ]
