# Generated by Django 4.0.3 on 2022-04-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinnworksConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_import_file_path', models.CharField(max_length=250)),
                ('composition_import_file_path', models.CharField(max_length=250)),
                ('inventory_export_file_path', models.CharField(max_length=250)),
                ('composition_export_file_path', models.CharField(max_length=250)),
                ('image_export_file_path', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Linnworks Config',
            },
        ),
    ]
