# Generated by Django 4.2.4 on 2023-08-15 11:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0030_alter_productsale_channel_sku_and_more"),
        (
            "orders",
            "0001_squashed_0028_rename_channel_order_id_order_external_reference_and_more",
        ),
        ("inventory", "0008_alter_baseproduct_barcode"),
        ("shipping", "0024_alter_exchangerate_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinnworksChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=255)),
                ("sub_source", models.CharField(max_length=255)),
                ("link_prime", models.BooleanField(default=False)),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="linnworks_channel",
                        to="orders.channel",
                    ),
                ),
                ("item_link_format", models.CharField(blank=True, max_length=255)),
                ("readable_name", models.CharField(blank=True, max_length=255)),
                ("link_by_sku", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Linnworks Channel",
                "verbose_name_plural": "Linnworks Channels",
                "ordering": ["source", "sub_source"],
                "unique_together": {("source", "sub_source")},
            },
        ),
        migrations.CreateModel(
            name="LinkingIgnoredSKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=255)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ignored_linking_skus",
                        to="linnworks.linnworkschannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linking Ignored SKU",
                "verbose_name_plural": "Linking Ignored SKUs",
            },
        ),
        migrations.CreateModel(
            name="InitialStockLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(db_index=True, max_length=255, unique=True)),
                ("stock_level", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Initial Stock Level",
                "verbose_name_plural": "Initial Stock Levels",
            },
        ),
        migrations.CreateModel(
            name="StockLevelExportUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("export_time", models.DateTimeField(unique=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Stock Level Export Update",
                "verbose_name_plural": "Stock Level Export Updates",
                "ordering": ["-export_time"],
                "get_latest_by": "export_time",
            },
        ),
        migrations.CreateModel(
            name="StockLevelExportRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_order_book", models.PositiveIntegerField()),
                ("stock_level", models.PositiveIntegerField()),
                ("purchase_price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("stock_value", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_level_records",
                        to="inventory.baseproduct",
                    ),
                ),
                (
                    "stock_level_update",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_level_records",
                        to="linnworks.stocklevelexportupdate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Level Export Record",
                "verbose_name_plural": "Stock Levels Export Records",
                "order_with_respect_to": "stock_level_update",
                "unique_together": {("stock_level_update", "product")},
                "get_latest_by": "stock_level_update__export_time",
            },
        ),
        migrations.CreateModel(
            name="LinnworksOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_guid", models.CharField(max_length=36)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linnworks_order",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linnworks Order",
                "verbose_name_plural": "Linnworks Orders",
            },
        ),
        migrations.CreateModel(
            name="LinnworksConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inventory_import_file_path",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "composition_import_file_path",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "inventory_export_file_path",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "composition_export_file_path",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "image_export_file_path",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "channel_items_export_file_path",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "channel_items_import_file_path",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "processed_orders_import_path",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "stock_level_export_file_path",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "last_image_update",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022, 7, 6, 13, 10, 56, 31399, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "image_import_file_path",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
            options={
                "verbose_name": "Linnworks Config",
            },
        ),
        migrations.CreateModel(
            name="LinnworksShippingService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "shipping_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="linnworks_shipping_services",
                        to="shipping.shippingservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linnworks Shipping Service",
                "verbose_name_plural": "Linnworks Shipping Services",
            },
        ),
    ]
