# Generated by Django 4.0.4 on 2022-04-27 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linnworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linnworksconfig',
            name='channel_items_export_file_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='linnworksconfig',
            name='channel_items_import_file_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='linnworksconfig',
            name='composition_export_file_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='linnworksconfig',
            name='composition_import_file_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='linnworksconfig',
            name='image_export_file_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='linnworksconfig',
            name='inventory_export_file_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='linnworksconfig',
            name='inventory_import_file_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='LinnworksChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('sub_source', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Linnworks Channel',
                'verbose_name_plural': 'Linnworks Channels',
                'ordering': ['source', 'sub_source'],
                'unique_together': {('source', 'sub_source')},
            },
        ),
        migrations.CreateModel(
            name='LinkingIgnoredSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_linking_skus', to='linnworks.linnworkschannel')),
            ],
            options={
                'verbose_name': 'Linking Ignored SKU',
                'verbose_name_plural': 'Linking Ignored SKUs',
            },
        ),
    ]
