# Generated by Django 4.0.4 on 2022-05-11 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linnworks', '0003_initialstocklevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initialstocklevel',
            options={'verbose_name': 'Initial Stock Level', 'verbose_name_plural': 'Initial Stock Levels'},
        ),
    ]
