# Generated by Django 4.0.4 on 2022-05-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linnworks', '0004_alter_initialstocklevel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='linnworkschannel',
            name='link_prime',
            field=models.BooleanField(default=False),
        ),
    ]
