# Generated by Django 4.0.4 on 2022-05-31 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_baseproduct_barcode'),
        ('linnworks', '0006_linnworkschannel_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLevelExportUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_time', models.DateTimeField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stock Level Export Update',
                'verbose_name_plural': 'Stock Level Export Updates',
                'ordering': ['-export_time'],
                'get_latest_by': 'export_time',
            },
        ),
        migrations.AddField(
            model_name='linnworksconfig',
            name='stock_level_export_file_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='StockLevelExportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_order_book', models.PositiveIntegerField()),
                ('stock_level', models.PositiveIntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock_value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_level_records', to='inventory.baseproduct')),
                ('stock_level_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_level_records', to='linnworks.stocklevelexportupdate')),
            ],
            options={
                'verbose_name': 'Stock Level Export Record',
                'verbose_name_plural': 'Stock Levels Export Records',
                'order_with_respect_to': 'stock_level_update',
                'unique_together': {('stock_level_update', 'product')},
            },
        ),
    ]
