# Generated by Django 4.0.5 on 2022-06-16 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_alter_productsale_channel_sku_and_more'),
        ('linnworks', '0008_alter_stocklevelexportrecord_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinnworksOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_guid', models.CharField(max_length=36)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linnworks_order', to='orders.order')),
            ],
        ),
    ]
