# Generated by Django 4.0.5 on 2022-06-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linnworks', '0009_linnworksorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linnworksorder',
            options={'verbose_name': 'Linnworks Order', 'verbose_name_plural': 'Linnworks Orders'},
        ),
    ]
