# Generated by Django 4.0.6 on 2022-07-06 13:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('linnworks', '0011_linnworkschannel_item_link_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linnworksconfig',
            name='last_image_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 13, 10, 56, 31399, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
