# Generated by Django 4.1.3 on 2022-11-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linnworks", "0014_linnworksshippingservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="linnworkschannel",
            name="link_by_sku",
            field=models.BooleanField(default=True),
        ),
    ]
