# Generated by Django 4.2.4 on 2023-08-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("linnworks", "0001_squashed_0015_linnworkschannel_link_by_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linnworksconfig",
            name="last_image_update",
            field=models.DateTimeField(),
        ),
    ]
