# Generated by Django 4.2.5 on 2023-09-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("linnworks", "0001_squashed_0016_alter_linnworksconfig_last_image_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="linnworksconfig",
            name="weight_compensation",
            field=models.PositiveIntegerField(default=20),
        ),
    ]
