# Generated by Django 5.1 on 2024-09-17 10:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0012_staff_can_clock_in"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoursExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_date",
                    models.DateField(default=django.utils.timezone.now, unique=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("report_sent", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Hours Export",
                "verbose_name_plural": "Hours Exports",
                "ordering": ("-export_date",),
            },
        ),
        migrations.CreateModel(
            name="HoursSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("send_report_to", models.EmailField(max_length=254, null=True)),
            ],
            options={
                "verbose_name": "Hours Settings",
            },
        ),
        migrations.CreateModel(
            name="ClockTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clock_hours",
                        to="home.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clock Time",
                "verbose_name_plural": "Clock Times",
                "ordering": ("timestamp",),
                "get_latest_by": "timestamp",
                "unique_together": {("user", "timestamp")},
            },
        ),
    ]
