# Generated by Django 5.1 on 2024-08-29 09:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0012_staff_can_clock_in"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClockTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clock_hours",
                        to="home.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clock Time",
                "verbose_name_plural": "Clock Times",
                "ordering": ("timestamp",),
                "get_latest_by": "timestamp",
                "unique_together": {("user", "timestamp")},
            },
        ),
    ]
