# Generated by Django 3.1.11 on 2021-05-27 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComputerMaintainanceJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField()),
                ("cleaned", models.BooleanField()),
                ("os_reinstalled", models.BooleanField()),
                ("notes", models.TextField(blank=True)),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hardware.computer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Computer Maintainance Job",
                "verbose_name_plural": "Computer Maintainance Jobs",
                "ordering": ["completed_at"],
            },
        ),
    ]
