# Generated by Django 3.1.11 on 2021-05-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0002_computermaintainancejob"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="computermaintainancejob",
            options={
                "ordering": ["-completed_at"],
                "verbose_name": "Computer Maintainance Job",
                "verbose_name_plural": "Computer Maintainance Jobs",
            },
        ),
    ]
