# Generated by Django 5.0.1 on 2024-01-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0001_squashed_0004_auto_20210601_1017"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gpu",
            name="manufacturer",
            field=models.CharField(
                choices=[("Intel", "Intel"), ("AMD", "AMD"), ("NVIDIA", "NVIDIA")],
                max_length=50,
            ),
        ),
    ]
