# Generated by Django 2.1.2 on 2018-10-02 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WowcherDeal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deal_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("product_SKU", models.CharField(max_length=255)),
                ("product_ID", models.CharField(max_length=255)),
                ("item_net", models.DecimalField(decimal_places=2, max_digits=6)),
                ("item_gross", models.DecimalField(decimal_places=2, max_digits=6)),
                ("total_net", models.DecimalField(decimal_places=2, max_digits=6)),
                ("total_gross", models.DecimalField(decimal_places=2, max_digits=6)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("ended", models.DateTimeField(blank=True, default=None, null=True)),
                ("inactive", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Wowcher Deal",
                "verbose_name_plural": "Wowcher Deals",
                "ordering": ("created",),
            },
        ),
        migrations.CreateModel(
            name="WowcherOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wowcher_code", models.CharField(max_length=255)),
                (
                    "cloud_commerce_order_ID",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("status_received_by_merchant", "Recieved by merchant"),
                            ("status_ready_for_despatch", "Ready for dispatch"),
                            ("status_despatched", "Dispatched"),
                        ],
                        max_length=50,
                    ),
                ),
                ("canceled", models.BooleanField(default=False)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wowcher.WowcherDeal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wowcher Order",
                "verbose_name_plural": "Wowcher Orders",
            },
        ),
    ]
