# Generated by Django 2.2.1 on 2019-05-13 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WowcherDeal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deal_ID",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("shipping_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("ended", models.DateTimeField(blank=True, default=None, null=True)),
                ("inactive", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Wowcher Deal",
                "verbose_name_plural": "Wowcher Deals",
                "ordering": ("created",),
            },
        ),
        migrations.CreateModel(
            name="WowcherItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wowcher_ID",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("CC_SKU", models.CharField(max_length=12)),
                ("CC_product_ID", models.CharField(max_length=20)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wowcher.WowcherDeal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wowcher Item",
                "verbose_name_plural": "Wowcher Items",
            },
        ),
        migrations.CreateModel(
            name="WowcherProofOfDeliveryFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Wowcher Proof of Delivery File",
                "verbose_name_plural": "Wowcher Proof of Delivery Files",
                "ordering": ("time_created",),
            },
        ),
        migrations.CreateModel(
            name="WowcherRedemptionFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Wowcher Redemption File",
                "verbose_name_plural": "Wowcher Redemption Files",
                "ordering": ("time_created",),
            },
        ),
        migrations.CreateModel(
            name="WowcherOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wowcher_code",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("customer_name", models.CharField(max_length=255)),
                (
                    "CC_order_ID",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "CC_customer_ID",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField()),
                ("dispatched", models.BooleanField(default=False)),
                ("canceled", models.BooleanField(default=False)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wowcher.WowcherDeal",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wowcher.WowcherItem",
                    ),
                ),
                (
                    "proof_of_delivery_file",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wowcher.WowcherProofOfDeliveryFile",
                    ),
                ),
                (
                    "redemption_file",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wowcher.WowcherRedemptionFile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wowcher Order",
                "verbose_name_plural": "Wowcher Orders",
                "ordering": ("time_created",),
            },
        ),
    ]
