# Generated by Django 2.2.1 on 2019-05-13 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wowcher", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="wowcherdeal",
            name="stock_alert_level",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="wowcheritem",
            name="hide_stock_alert",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="WowcherStockLevelCheck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_level", models.PositiveSmallIntegerField()),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wowcher.WowcherItem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wowcher Stock Level",
                "verbose_name_plural": "Wowcher Stock Levels",
                "ordering": ("timestamp",),
            },
        ),
    ]
