# Generated by Django 2.2.1 on 2019-05-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("wowcher", "0002_auto_20190513_1548")]

    operations = [
        migrations.RenameModel(
            old_name="WowcherRedemptionFile", new_name="WowcherDeliveryStatusFile"
        ),
        migrations.AlterModelOptions(
            name="wowcherdeliverystatusfile",
            options={
                "ordering": ("time_created",),
                "verbose_name": "Wowcher Delivery Status File",
                "verbose_name_plural": "Wowcher Delivery Status Files",
            },
        ),
        migrations.RenameField(
            model_name="wowcherorder",
            old_name="redemption_file",
            new_name="delivery_status_file",
        ),
    ]
