# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-24 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STCAdminImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_id', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to=inventory.models.get_product_image_upload_to)),
            ],
        ),
    ]
