# Generated by Django 2.2.4 on 2019-08-12 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import inventory.models.product_exports


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="STCAdminImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("range_id", models.CharField(max_length=10)),
                ("image", models.ImageField()),
            ],
            options={
                "verbose_name": "STC Admin Image",
                "verbose_name_plural": "STC Admin Images",
            },
        ),
        migrations.CreateModel(
            name="Barcode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=13, unique=True)),
                ("used", models.BooleanField(default=False)),
            ],
            options={"verbose_name": "Barcode", "verbose_name_plural": "Barcodes"},
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                ("warehouse_ID", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "abriviation",
                    models.CharField(blank=True, max_length=4, null=True, unique=True),
                ),
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse",
                "verbose_name_plural": "Warehouses",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="StockChange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("product_sku", models.CharField(max_length=11)),
                ("product_id", models.CharField(max_length=50)),
                ("stock_before", models.PositiveIntegerField()),
                ("stock_after", models.PositiveIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Change",
                "verbose_name_plural": "Stock Changes",
            },
        ),
        migrations.CreateModel(
            name="ProductExport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("timestamp", models.DateTimeField()),
                (
                    "export_file",
                    models.FileField(
                        upload_to=inventory.models.product_exports.export_file_path
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Export",
                "verbose_name_plural": "Product Exports",
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("product_option_ID", models.CharField(max_length=20, unique=True)),
                ("factory_ID", models.CharField(max_length=20, unique=True)),
                ("inactive", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "ordering": ("inactive", "name"),
            },
        ),
        migrations.CreateModel(
            name="SupplierContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("phone", models.CharField(blank=True, max_length=200, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Contact",
                "verbose_name_plural": "Supplier Contacts",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("product_option_ID", models.CharField(max_length=20, unique=True)),
                ("inactive", models.BooleanField(default=False)),
                ("abriviation", models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ("inactive", "name"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InternationalShipping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, db_index=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("product_option_ID", models.CharField(max_length=20, unique=True)),
                ("inactive", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "International Shipping",
                "verbose_name_plural": "International Shipping",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PackageType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, db_index=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("product_option_ID", models.CharField(max_length=20, unique=True)),
                ("inactive", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Package Type",
                "verbose_name_plural": "Package Types",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Bay",
            fields=[
                ("bay_ID", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.Warehouse",
                    ),
                ),
            ],
            options={"verbose_name": "Bay", "verbose_name_plural": "Bays"},
        ),
    ]
