# Generated by Django 4.0.1 on 2022-02-01 11:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("inventory", "0001_initial"),
        ("inventory", "0002_auto_20190911_1026"),
        ("inventory", "0003_auto_20200123_1027"),
        ("inventory", "0004_auto_20200218_1156"),
        ("inventory", "0005_delete_stcadminimage"),
        ("inventory", "0006_packagetype_description"),
        ("inventory", "0007_auto_20210601_1017"),
        ("inventory", "0008_productimage"),
        ("inventory", "0009_delete_productimage"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="STCAdminImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("range_id", models.CharField(max_length=10)),
                ("image", models.ImageField(upload_to="")),
            ],
            options={
                "verbose_name": "STC Admin Image",
                "verbose_name_plural": "STC Admin Images",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                ("warehouse_ID", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "abriviation",
                    models.CharField(blank=True, max_length=4, null=True, unique=True),
                ),
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse",
                "verbose_name_plural": "Warehouses",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="StockChange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("product_sku", models.CharField(max_length=11)),
                ("product_id", models.CharField(max_length=50)),
                ("stock_before", models.PositiveIntegerField()),
                ("stock_after", models.PositiveIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Change",
                "verbose_name_plural": "Stock Changes",
            },
        ),
        migrations.CreateModel(
            name="ProductExport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("timestamp", models.DateTimeField()),
                (
                    "export_file",
                    models.FileField(),
                ),
            ],
            options={
                "verbose_name": "Product Export",
                "verbose_name_plural": "Product Exports",
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "product_option_value_ID",
                    models.CharField(max_length=20, unique=True),
                ),
                ("factory_ID", models.CharField(max_length=20, unique=True)),
                ("inactive", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "ordering": ("inactive", "name"),
            },
        ),
        migrations.CreateModel(
            name="SupplierContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("phone", models.CharField(blank=True, max_length=200, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Contact",
                "verbose_name_plural": "Supplier Contacts",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Barcode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=13, unique=True)),
                (
                    "added_on",
                    models.DateTimeField(
                        auto_now_add=True, default=django.utils.timezone.now
                    ),
                ),
                ("available", models.BooleanField(default=True)),
                (
                    "used_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("used_for", models.TextField(null=True)),
                ("used_on", models.DateTimeField(null=True)),
            ],
            options={
                "verbose_name": "Barcode",
                "verbose_name_plural": "Barcodes",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "product_option_value_ID",
                    models.CharField(max_length=20, unique=True),
                ),
                ("inactive", models.BooleanField(default=False)),
                ("abriviation", models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InternationalShipping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "product_option_value_ID",
                    models.CharField(max_length=20, unique=True),
                ),
                ("inactive", models.BooleanField(default=False)),
                ("ordering", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "International Shipping",
                "verbose_name_plural": "International Shipping",
                "ordering": ["ordering"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Bay",
            fields=[
                ("bay_ID", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.warehouse",
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Bay",
                "verbose_name_plural": "Bays",
                "ordering": ("-is_default", "name"),
            },
        ),
        migrations.CreateModel(
            name="PackageType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "product_option_value_ID",
                    models.CharField(max_length=20, unique=True),
                ),
                ("inactive", models.BooleanField(default=False)),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("large_letter_compatible", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Package Type",
                "verbose_name_plural": "Package Types",
                "ordering": ["ordering"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="bay",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("warehouse",),
                name="single_default_bay_per_warehouse",
            ),
        ),
        migrations.DeleteModel(
            name="STCAdminImage",
        ),
        migrations.AddField(
            model_name="packagetype",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="barcode",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="bay",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="internationalshipping",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="packagetype",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="productexport",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stockchange",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="suppliercontact",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
