# Generated by Django 4.0.1 on 2022-02-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial_squashed_0009_delete_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barcode",
            name="added_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
