# Generated by Django 4.0.1 on 2022-02-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0002_alter_barcode_added_on")]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=20)),
                ("range_sku", models.CharField(max_length=20)),
                ("sku", models.CharField(max_length=20)),
                ("cloud_commerce_name", models.CharField(max_length=50)),
                ("position", models.PositiveIntegerField()),
                ("image_file", models.ImageField(upload_to="")),
            ],
        ),
    ]
