# Generated by Django 2.1.4 on 2018-12-04 15:35

from django.db import migrations, models

import inventory.models.product_exports


class Migration(migrations.Migration):

    dependencies = [("inventory", "0002_stockchange")]

    operations = [
        migrations.CreateModel(
            name="ProductExport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("timestamp", models.DateTimeField()),
                (
                    "export_file",
                    models.FileField(
                        upload_to=inventory.models.product_exports.export_file_path
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Export",
                "verbose_name_plural": "Product Exports",
                "ordering": ("timestamp",),
            },
        )
    ]
