# Generated by Django 2.2.4 on 2019-08-12 14:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import inventory.models.products


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0002_auto_20190911_1026"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_option_value_ID",
                    models.CharField(max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("inactive", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "34321",
                "verbose_name_plural": "Brands",
                "ordering": ("inactive", "name"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, db_index=True)),
                (
                    "product_option_value_ID",
                    models.CharField(max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("inactive", models.BooleanField(default=False)),
                ("readable_name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Gender",
                "verbose_name_plural": "Genders",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_option_value_ID",
                    models.CharField(max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("inactive", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Manufacturer",
                "verbose_name_plural": "Manufacturers",
                "ordering": ("inactive", "name"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PartialProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_ID", models.CharField(max_length=50, null=True, unique=True)),
                ("SKU", models.CharField(max_length=255, null=True, unique=True)),
                (
                    "supplier_SKU",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("barcode", models.CharField(max_length=20, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "retail_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("weight_grams", models.PositiveSmallIntegerField(null=True)),
                ("length_mm", models.PositiveSmallIntegerField(null=True)),
                ("height_mm", models.PositiveSmallIntegerField(null=True)),
                ("width_mm", models.PositiveSmallIntegerField(null=True)),
                ("multipack", models.BooleanField(default=False)),
                ("end_of_line", models.BooleanField(default=False)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("range_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("creating", "Creating"),
                            ("updating", "Updating"),
                            ("error", "Error"),
                        ],
                        default="creating",
                        max_length=20,
                    ),
                ),
                ("date_created", models.DateField(auto_now_add=True)),
                ("pre_existing", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Partial Product",
                "verbose_name_plural": "Partial Products",
            },
            bases=(models.Model, inventory.models.products.BaseProductModel),
        ),
        migrations.CreateModel(
            name="PartialProductOptionValueLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
            options={
                "verbose_name": "Partial Product Option Value Link",
                "verbose_name_plural": "Partial Product Option Value Links",
                "ordering": ("product_option_value__product_option",),
            },
        ),
        migrations.CreateModel(
            name="PartialProductRange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("range_ID", models.CharField(max_length=50, null=True, unique=True)),
                (
                    "SKU",
                    models.CharField(
                        db_index=True, max_length=15, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("amazon_search_terms", models.TextField(blank=True, default="")),
                ("amazon_bullet_points", models.TextField(blank=True, default="")),
                ("end_of_line", models.BooleanField(default=False)),
                ("hidden", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Partial Product Range",
                "verbose_name_plural": "Partial Product Ranges",
            },
            bases=(models.Model, inventory.models.products.BaseProductRangeModel),
        ),
        migrations.CreateModel(
            name="PartialProductRangeSelectedOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variation", models.BooleanField()),
                ("pre_existing", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Partial Product Range Selected Option",
                "verbose_name_plural": "Partial Product Range Selected Options",
                "ordering": ("product_option",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_ID",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("SKU", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "supplier_SKU",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("barcode", models.CharField(max_length=20)),
                ("purchase_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "retail_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("weight_grams", models.PositiveSmallIntegerField()),
                ("length_mm", models.PositiveSmallIntegerField()),
                ("height_mm", models.PositiveSmallIntegerField()),
                ("width_mm", models.PositiveSmallIntegerField()),
                ("multipack", models.BooleanField(default=False)),
                ("end_of_line", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("creating", "Creating"),
                            ("updating", "Updating"),
                            ("error", "Error"),
                        ],
                        default="creating",
                        max_length=20,
                    ),
                ),
                ("date_created", models.DateField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("range_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
            bases=(models.Model, inventory.models.products.BaseProductModel),
        ),
        migrations.CreateModel(
            name="ProductEdit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
            options={
                "verbose_name": "Product Edit",
                "verbose_name_plural": "Product Edits",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_ID",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("filename", models.CharField(max_length=200)),
                ("URL", models.URLField()),
                ("position", models.PositiveSmallIntegerField()),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ("position",),
            },
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, db_index=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("product_option_ID", models.CharField(max_length=20, unique=True)),
                ("inactive", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Product Option",
                "verbose_name_plural": "Product Options",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductOptionValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_option_value_ID",
                    models.CharField(max_length=20, unique=True),
                ),
                ("value", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Product Option Value",
                "verbose_name_plural": "Product Option Values",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductOptionValueLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
            options={
                "verbose_name": "ProductOptionValueLink",
                "verbose_name_plural": "ProductOptionValueLinks",
                "ordering": ("product_option_value__product_option",),
            },
        ),
        migrations.CreateModel(
            name="ProductRange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "range_ID",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("SKU", models.CharField(db_index=True, max_length=15, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("amazon_search_terms", models.TextField(blank=True, default="")),
                ("amazon_bullet_points", models.TextField(blank=True, default="")),
                ("end_of_line", models.BooleanField(default=False)),
                ("hidden", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Product Range",
                "verbose_name_plural": "Product Ranges",
            },
            bases=(models.Model, inventory.models.products.BaseProductRangeModel),
        ),
        migrations.CreateModel(
            name="ProductRangeSelectedOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variation", models.BooleanField()),
            ],
            options={
                "verbose_name": "ProductRangeSelectedOption",
                "verbose_name_plural": "ProductRangeSelectedOptions",
                "ordering": ("product_option",),
            },
        ),
        migrations.CreateModel(
            name="VATRate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, db_index=True)),
                ("VAT_rate_ID", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "percentage",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "VAT Rate",
                "verbose_name_plural": "VAT Rates",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.DeleteModel(name="STCAdminImage"),
        migrations.AlterModelOptions(
            name="bay",
            options={
                "ordering": ("-is_default", "name"),
                "verbose_name": "Bay",
                "verbose_name_plural": "Bays",
            },
        ),
        migrations.RenameField(
            model_name="department",
            old_name="product_option_ID",
            new_name="product_option_value_ID",
        ),
        migrations.RenameField(
            model_name="internationalshipping",
            old_name="product_option_ID",
            new_name="product_option_value_ID",
        ),
        migrations.RenameField(
            model_name="packagetype",
            old_name="product_option_ID",
            new_name="product_option_value_ID",
        ),
        migrations.RenameField(
            model_name="supplier",
            old_name="product_option_ID",
            new_name="product_option_value_ID",
        ),
        migrations.AddField(
            model_name="bay",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="packagetype",
            name="large_letter_compatible",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="bay",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_default=True),
                fields=("warehouse",),
                name="single_default_bay_per_warehouse",
            ),
        ),
        migrations.AddField(
            model_name="productrangeselectedoption",
            name="product_option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.ProductOption",
            ),
        ),
        migrations.AddField(
            model_name="productrangeselectedoption",
            name="product_range",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.ProductRange"
            ),
        ),
        migrations.AddField(
            model_name="productrange",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.Department"
            ),
        ),
        migrations.AddField(
            model_name="productrange",
            name="product_options",
            field=models.ManyToManyField(
                blank=True,
                through="inventory.ProductRangeSelectedOption",
                to="inventory.ProductOption",
            ),
        ),
        migrations.AddField(
            model_name="productoptionvaluelink",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.Product"
            ),
        ),
        migrations.AddField(
            model_name="productoptionvaluelink",
            name="product_option_value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.ProductOptionValue",
            ),
        ),
        migrations.AddField(
            model_name="productoptionvalue",
            name="product_option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.ProductOption",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.Product"
            ),
        ),
        migrations.AddField(
            model_name="productedit",
            name="partial_product_range",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.PartialProductRange",
            ),
        ),
        migrations.AddField(
            model_name="productedit",
            name="product_option_values",
            field=models.ManyToManyField(to="inventory.ProductOptionValue"),
        ),
        migrations.AddField(
            model_name="productedit",
            name="product_range",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.ProductRange"
            ),
        ),
        migrations.AddField(
            model_name="productedit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="VAT_rate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.VATRate"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="bays",
            field=models.ManyToManyField(blank=True, to="inventory.Bay"),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.Brand"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.Gender",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="international_shipping",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.InternationalShipping",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.Manufacturer"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="package_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.PackageType"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_options",
            field=models.ManyToManyField(
                blank=True,
                through="inventory.ProductOptionValueLink",
                to="inventory.ProductOptionValue",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_range",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.ProductRange"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.Supplier"
            ),
        ),
        migrations.AddField(
            model_name="partialproductrangeselectedoption",
            name="product_option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.ProductOption",
            ),
        ),
        migrations.AddField(
            model_name="partialproductrangeselectedoption",
            name="product_range",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.PartialProductRange",
            ),
        ),
        migrations.AddField(
            model_name="partialproductrange",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.Department",
            ),
        ),
        migrations.AddField(
            model_name="partialproductrange",
            name="original_range",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.ProductRange",
            ),
        ),
        migrations.AddField(
            model_name="partialproductrange",
            name="product_options",
            field=models.ManyToManyField(
                blank=True,
                through="inventory.PartialProductRangeSelectedOption",
                to="inventory.ProductOption",
            ),
        ),
        migrations.AddField(
            model_name="partialproductoptionvaluelink",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.PartialProduct",
            ),
        ),
        migrations.AddField(
            model_name="partialproductoptionvaluelink",
            name="product_option_value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.ProductOptionValue",
            ),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="VAT_rate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.VATRate",
            ),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="bays",
            field=models.ManyToManyField(blank=True, to="inventory.Bay"),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.Brand",
            ),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.Gender",
            ),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="international_shipping",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.InternationalShipping",
            ),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="manufacturer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.Manufacturer",
            ),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="original_product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.Product",
            ),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="package_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.PackageType",
            ),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="product_options",
            field=models.ManyToManyField(
                blank=True,
                through="inventory.PartialProductOptionValueLink",
                to="inventory.ProductOptionValue",
            ),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="product_range",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.PartialProductRange",
            ),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.Supplier",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productrangeselectedoption",
            unique_together={("product_range", "product_option")},
        ),
        migrations.AlterUniqueTogether(
            name="productoptionvaluelink",
            unique_together={("product", "product_option_value")},
        ),
        migrations.AlterUniqueTogether(
            name="productoptionvalue", unique_together={("product_option", "value")}
        ),
        migrations.AlterUniqueTogether(
            name="partialproductrangeselectedoption",
            unique_together={("product_range", "product_option")},
        ),
        migrations.AlterUniqueTogether(
            name="partialproductoptionvaluelink",
            unique_together={("product", "product_option_value")},
        ),
    ]
