# Generated by Django 3.0.2 on 2020-01-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0002_auto_20190911_1026")]

    operations = [
        migrations.AlterModelOptions(
            name="internationalshipping",
            options={
                "ordering": ("ordering",),
                "verbose_name": "International Shipping",
                "verbose_name_plural": "International Shipping",
            },
        ),
        migrations.AlterModelOptions(
            name="packagetype",
            options={
                "ordering": ("ordering",),
                "verbose_name": "Package Type",
                "verbose_name_plural": "Package Types",
            },
        ),
        migrations.RemoveField(model_name="internationalshipping", name="sort_order"),
        migrations.RemoveField(model_name="packagetype", name="sort_order"),
        migrations.AddField(
            model_name="internationalshipping",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="packagetype",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
