# Generated by Django 2.0 on 2017-12-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20171220_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, default='nope', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='range_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Range ID'),
        ),
    ]
