# Generated by Django 2.1.4 on 2018-12-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("inventory", "0003_productexport")]

    operations = [
        migrations.AlterModelOptions(
            name="productexport",
            options={
                "ordering": ("-timestamp",),
                "verbose_name": "Product Export",
                "verbose_name_plural": "Product Exports",
            },
        )
    ]
