# Generated by Django 3.0.3 on 2020-02-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0003_auto_20200123_1027")]

    operations = [
        migrations.AlterModelOptions(
            name="bay",
            options={
                "ordering": ("-is_default", "name"),
                "verbose_name": "Bay",
                "verbose_name_plural": "Bays",
            },
        ),
        migrations.AlterModelOptions(
            name="department",
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.AlterModelOptions(
            name="internationalshipping",
            options={
                "ordering": ["ordering"],
                "verbose_name": "International Shipping",
                "verbose_name_plural": "International Shipping",
            },
        ),
        migrations.AlterModelOptions(
            name="packagetype",
            options={
                "ordering": ["ordering"],
                "verbose_name": "Package Type",
                "verbose_name_plural": "Package Types",
            },
        ),
        migrations.RenameField(
            model_name="department",
            old_name="product_option_ID",
            new_name="product_option_value_ID",
        ),
        migrations.RenameField(
            model_name="internationalshipping",
            old_name="product_option_ID",
            new_name="product_option_value_ID",
        ),
        migrations.RenameField(
            model_name="packagetype",
            old_name="product_option_ID",
            new_name="product_option_value_ID",
        ),
        migrations.RenameField(
            model_name="supplier",
            old_name="product_option_ID",
            new_name="product_option_value_ID",
        ),
        migrations.AddField(
            model_name="bay",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="packagetype",
            name="large_letter_compatible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="bay",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_default=True),
                fields=("warehouse",),
                name="single_default_bay_per_warehouse",
            ),
        ),
    ]
