# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_packagetype_shippingprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingprice',
            name='price',
        ),
        migrations.AddField(
            model_name='shippingprice',
            name='item_price',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingprice',
            name='kilo_price',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
