# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20171115_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingprice',
            name='package_type',
        ),
        migrations.AddField(
            model_name='shippingprice',
            name='package_type',
            field=models.ManyToManyField(to='inventory.PackageType'),
        ),
    ]
