# Generated by Django 4.0.3 on 2022-04-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_baseproduct_brand_combinationproductlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
