# Generated by Django 4.0.3 on 2022-03-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_baseproduct_brand_combinationproductlink_gender_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="gender",
        ),
        migrations.DeleteModel(
            name="Gender",
        ),
    ]
