# Generated by Django 3.0.3 on 2020-02-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("inventory", "0004_auto_20200218_1156")]

    operations = [migrations.DeleteModel(name="STCAdminImage")]
