# Generated by Django 4.0.3 on 2022-03-16 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_baseproduct_brand_combinationproductlink_gender_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductRangeImageLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_ranges",
                        to="inventory.productimage",
                    ),
                ),
                (
                    "product_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="inventory.productrange",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Range Image Link",
                "verbose_name_plural": "Product Range Image Links",
                "ordering": ("ordering",),
                "unique_together": {("product_range", "image")},
            },
        ),
        migrations.CreateModel(
            name="ProductImageLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="inventory.productimage",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="inventory.baseproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image Link",
                "verbose_name_plural": "Product Image Links",
                "ordering": ("ordering",),
                "unique_together": {("product", "image")},
            },
        ),
    ]
