# Generated by Django 3.0.2 on 2020-01-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0004_auto_20190903_0958")]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name": "34321", "verbose_name_plural": "Brands"},
        ),
        migrations.AlterModelOptions(
            name="department",
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.AlterModelOptions(
            name="gender",
            options={
                "ordering": ["ordering"],
                "verbose_name": "Gender",
                "verbose_name_plural": "Genders",
            },
        ),
        migrations.AlterModelOptions(
            name="internationalshipping",
            options={
                "ordering": ["ordering"],
                "verbose_name": "International Shipping",
                "verbose_name_plural": "International Shipping",
            },
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={
                "verbose_name": "Manufacturer",
                "verbose_name_plural": "Manufacturers",
            },
        ),
        migrations.AlterModelOptions(
            name="packagetype",
            options={
                "ordering": ["ordering"],
                "verbose_name": "Package Type",
                "verbose_name_plural": "Package Types",
            },
        ),
        migrations.AlterModelOptions(
            name="productoption",
            options={
                "ordering": ["ordering"],
                "verbose_name": "Product Option",
                "verbose_name_plural": "Product Options",
            },
        ),
        migrations.AlterModelOptions(
            name="vatrate",
            options={
                "ordering": ["ordering"],
                "verbose_name": "VAT Rate",
                "verbose_name_plural": "VAT Rates",
            },
        ),
        migrations.RemoveField(model_name="gender", name="sort_order"),
        migrations.RemoveField(model_name="internationalshipping", name="sort_order"),
        migrations.RemoveField(model_name="packagetype", name="sort_order"),
        migrations.RemoveField(model_name="productoption", name="sort_order"),
        migrations.RemoveField(model_name="vatrate", name="sort_order"),
        migrations.AddField(
            model_name="gender",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="internationalshipping",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="packagetype",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productoption",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vatrate",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="packagetype",
            name="large_letter_compatible",
            field=models.BooleanField(default=False),
        ),
    ]
