# Generated by Django 4.0.3 on 2022-03-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_baseproduct_brand_combinationproductlink_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrange',
            old_name='amazon_bullet_points',
            new_name='bullet_points',
        ),
        migrations.RenameField(
            model_name='productrange',
            old_name='amazon_search_terms',
            new_name='search_terms',
        ),
    ]
