# Generated by Django 2.0 on 2017-12-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20171221_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='range_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Range ID'),
        ),
    ]
