# Generated by Django 4.0.3 on 2022-03-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_baseproduct_brand_combinationproductlink_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseproduct',
            options={'base_manager_name': 'objects', 'ordering': ('product_range', 'range_order'), 'verbose_name': 'Base Product', 'verbose_name_plural': 'Base Products'},
        ),
    ]
