# Generated by Django 2.1.4 on 2018-12-10 10:48

import os
from pathlib import Path

from django.conf import settings
from django.db import migrations


def move_export_files(apps, schema_editor):
    """Update the location of the saved Product export files."""
    from inventory.models.product_exports import export_file_path

    ProductExport = apps.get_model("inventory", "ProductExport")
    for export in ProductExport.objects.all():
        media_root = Path(settings.MEDIA_ROOT)
        old_path = export.export_file.path
        new_name = Path(export_file_path(export, None))
        new_path = media_root / new_name
        new_path.parent.mkdir(parents=True, exist_ok=True)
        os.rename(old_path, new_path)
        export.export_file.name = str(new_name)
        export.save()
        remove_directory_recursive(old_path)


def remove_directory_recursive(path):
    """Remove empty directories."""
    if path.is_dir() and len(os.listdir(path)) == 0:
        os.rmdir(path)
        remove_directory_recursive(path.parent)


class Migration(migrations.Migration):

    dependencies = [("inventory", "0004_sort_product_export")]

    operations = [migrations.RunPython(move_export_files)]
