# Generated by Django 3.1.14 on 2022-03-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_auto_20220301_1200"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_ID",
        ),
        migrations.RemoveField(
            model_name="productrange",
            name="range_ID",
        ),
        migrations.RemoveField(
            model_name="stockchange",
            name="product_id",
        ),
    ]
