# Generated by Django 3.0.3 on 2020-02-24 12:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import inventory.models.products


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0005_delete_stcadminimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_option_value_ID",
                    models.CharField(max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("inactive", models.BooleanField(default=False)),
            ],
            options={"verbose_name": "34321", "verbose_name_plural": "Brands"},
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_option_value_ID",
                    models.CharField(max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("inactive", models.BooleanField(default=False)),
                ("readable_name", models.CharField(max_length=50)),
                ("ordering", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Gender",
                "verbose_name_plural": "Genders",
                "ordering": ["ordering"],
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_option_value_ID",
                    models.CharField(max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("inactive", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Manufacturer",
                "verbose_name_plural": "Manufacturers",
            },
        ),
        migrations.CreateModel(
            name="PartialProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_ID", models.CharField(max_length=50, null=True, unique=True)),
                ("SKU", models.CharField(max_length=255, null=True, unique=True)),
                (
                    "supplier_SKU",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("barcode", models.CharField(max_length=20, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "retail_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("weight_grams", models.PositiveSmallIntegerField(null=True)),
                ("length_mm", models.PositiveSmallIntegerField(null=True)),
                ("height_mm", models.PositiveSmallIntegerField(null=True)),
                ("width_mm", models.PositiveSmallIntegerField(null=True)),
                ("multipack", models.BooleanField(default=False)),
                ("end_of_line", models.BooleanField(default=False)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("range_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("creating", "Creating"),
                            ("updating", "Updating"),
                            ("error", "Error"),
                        ],
                        default="creating",
                        max_length=20,
                    ),
                ),
                ("date_created", models.DateField(auto_now_add=True)),
                ("pre_existing", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Partial Product",
                "verbose_name_plural": "Partial Products",
            },
            bases=(inventory.models.products.BaseProductModel, models.Model),
        ),
        migrations.CreateModel(
            name="PartialProductRange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("range_ID", models.CharField(max_length=50, null=True, unique=True)),
                (
                    "SKU",
                    models.CharField(
                        db_index=True, max_length=15, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("amazon_search_terms", models.TextField(blank=True, default="")),
                ("amazon_bullet_points", models.TextField(blank=True, default="")),
                ("end_of_line", models.BooleanField(default=False)),
                ("hidden", models.BooleanField(default=False)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.Department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partial Product Range",
                "verbose_name_plural": "Partial Product Ranges",
            },
            bases=(inventory.models.products.BaseProductRangeModel, models.Model),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_ID",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("SKU", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "supplier_SKU",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("barcode", models.CharField(max_length=20)),
                ("purchase_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "retail_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("weight_grams", models.PositiveSmallIntegerField()),
                ("length_mm", models.PositiveSmallIntegerField()),
                ("height_mm", models.PositiveSmallIntegerField()),
                ("width_mm", models.PositiveSmallIntegerField()),
                ("multipack", models.BooleanField(default=False)),
                ("end_of_line", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("creating", "Creating"),
                            ("updating", "Updating"),
                            ("error", "Error"),
                        ],
                        default="creating",
                        max_length=20,
                    ),
                ),
                ("date_created", models.DateField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("range_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
            bases=(inventory.models.products.BaseProductModel, models.Model),
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("product_option_ID", models.CharField(max_length=20, unique=True)),
                ("inactive", models.BooleanField(default=False)),
                ("ordering", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Product Option",
                "verbose_name_plural": "Product Options",
                "ordering": ["ordering"],
            },
        ),
        migrations.CreateModel(
            name="ProductOptionValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_option_value_ID",
                    models.CharField(max_length=20, unique=True),
                ),
                ("value", models.CharField(max_length=255)),
                (
                    "product_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.ProductOption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Option Value",
                "verbose_name_plural": "Product Option Values",
                "abstract": False,
                "unique_together": {("product_option", "value")},
            },
        ),
        migrations.CreateModel(
            name="ProductRange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "range_ID",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("SKU", models.CharField(db_index=True, max_length=15, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("amazon_search_terms", models.TextField(blank=True, default="")),
                ("amazon_bullet_points", models.TextField(blank=True, default="")),
                ("end_of_line", models.BooleanField(default=False)),
                ("hidden", models.BooleanField(default=False)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.Department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Range",
                "verbose_name_plural": "Product Ranges",
            },
            bases=(inventory.models.products.BaseProductRangeModel, models.Model),
        ),
        migrations.CreateModel(
            name="VATRate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("VAT_rate_ID", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "percentage",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "VAT Rate",
                "verbose_name_plural": "VAT Rates",
                "ordering": ["ordering"],
            },
        ),
        migrations.CreateModel(
            name="ProductRangeSelectedOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variation", models.BooleanField()),
                (
                    "product_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.ProductOption",
                    ),
                ),
                (
                    "product_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.ProductRange",
                    ),
                ),
            ],
            options={
                "verbose_name": "ProductRangeSelectedOption",
                "verbose_name_plural": "ProductRangeSelectedOptions",
                "ordering": ("product_option",),
                "unique_together": {("product_range", "product_option")},
            },
        ),
        migrations.AddField(
            model_name="productrange",
            name="product_options",
            field=models.ManyToManyField(
                blank=True,
                through="inventory.ProductRangeSelectedOption",
                to="inventory.ProductOption",
            ),
        ),
        migrations.CreateModel(
            name="ProductOptionValueLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.Product",
                    ),
                ),
                (
                    "product_option_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.ProductOptionValue",
                    ),
                ),
            ],
            options={
                "verbose_name": "ProductOptionValueLink",
                "verbose_name_plural": "ProductOptionValueLinks",
                "ordering": ("product_option_value__product_option",),
                "unique_together": {("product", "product_option_value")},
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_ID",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("filename", models.CharField(max_length=200)),
                ("URL", models.URLField()),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ("position",),
            },
        ),
        migrations.CreateModel(
            name="ProductEdit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "partial_product_range",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.PartialProductRange",
                    ),
                ),
                (
                    "product_option_values",
                    models.ManyToManyField(to="inventory.ProductOptionValue"),
                ),
                (
                    "product_range",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.ProductRange",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Edit",
                "verbose_name_plural": "Product Edits",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="VAT_rate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.VATRate"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="bays",
            field=models.ManyToManyField(blank=True, to="inventory.Bay"),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.Brand"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.Gender",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="international_shipping",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.InternationalShipping",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.Manufacturer"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="package_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.PackageType"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_options",
            field=models.ManyToManyField(
                blank=True,
                through="inventory.ProductOptionValueLink",
                to="inventory.ProductOptionValue",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_range",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.ProductRange"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.Supplier"
            ),
        ),
        migrations.CreateModel(
            name="PartialProductRangeSelectedOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variation", models.BooleanField()),
                ("pre_existing", models.BooleanField(default=False)),
                (
                    "product_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.ProductOption",
                    ),
                ),
                (
                    "product_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.PartialProductRange",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partial Product Range Selected Option",
                "verbose_name_plural": "Partial Product Range Selected Options",
                "ordering": ("product_option",),
                "unique_together": {("product_range", "product_option")},
            },
        ),
        migrations.AddField(
            model_name="partialproductrange",
            name="original_range",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.ProductRange",
            ),
        ),
        migrations.AddField(
            model_name="partialproductrange",
            name="product_options",
            field=models.ManyToManyField(
                blank=True,
                through="inventory.PartialProductRangeSelectedOption",
                to="inventory.ProductOption",
            ),
        ),
        migrations.CreateModel(
            name="PartialProductOptionValueLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.PartialProduct",
                    ),
                ),
                (
                    "product_option_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.ProductOptionValue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partial Product Option Value Link",
                "verbose_name_plural": "Partial Product Option Value Links",
                "ordering": ("product_option_value__product_option",),
                "unique_together": {("product", "product_option_value")},
            },
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="VAT_rate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.VATRate",
            ),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="bays",
            field=models.ManyToManyField(blank=True, to="inventory.Bay"),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.Brand",
            ),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.Gender",
            ),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="international_shipping",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.InternationalShipping",
            ),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="manufacturer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.Manufacturer",
            ),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="original_product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.Product",
            ),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="package_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.PackageType",
            ),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="product_options",
            field=models.ManyToManyField(
                blank=True,
                through="inventory.PartialProductOptionValueLink",
                to="inventory.ProductOptionValue",
            ),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="product_range",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.PartialProductRange",
            ),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.Supplier",
            ),
        ),
    ]
