# Generated by Django 2.0 on 2018-01-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20171221_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bay',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bays',
        ),
        migrations.DeleteModel(
            name='Bay',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
