# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20171115_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shippingprice',
            name='country_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.DestinationCountry'),
        ),
    ]
