# Generated by Django 3.1.14 on 2022-03-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_auto_20220301_1211"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="SKU",
            new_name="sku",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="VAT_rate",
            new_name="vat_rate",
        ),
        migrations.RenameField(
            model_name="productrange",
            old_name="SKU",
            new_name="sku",
        ),
    ]
