# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20171115_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingprice',
            old_name='country_name',
            new_name='country',
        ),
    ]
