# Generated by Django 2.1.7 on 2019-02-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0006_supplier_suppliercontact")]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("product_option_ID", models.CharField(max_length=20, unique=True)),
                ("inactive", models.BooleanField(default=False)),
                ("abriviation", models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ("inactive", "name"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InternationalShipping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, db_index=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("product_option_ID", models.CharField(max_length=20, unique=True)),
                ("inactive", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "International Shipping",
                "verbose_name_plural": "International Shipping",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PackageType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, db_index=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("product_option_ID", models.CharField(max_length=20, unique=True)),
                ("inactive", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Package Type",
                "verbose_name_plural": "Package Types",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
