# Generated by Django 4.0.3 on 2022-04-06 12:01

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_productrange_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productrange',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='name_unique'),
        ),
    ]
