# Generated by Django 2.1.7 on 2019-02-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0007_department_internationalshipping_packagetype")]

    operations = [
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "ordering": ("inactive", "name"),
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
            },
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
