# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20171115_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingprice',
            name='kilo_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
