# Generated by Django 3.1.14 on 2022-03-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_auto_20220301_1435"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="listing_attribute",
            new_name="listing_attributes",
        ),
        migrations.RemoveField(
            model_name="product",
            name="multipack",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="product",
            name="hs_code",
            field=models.CharField(default="0", max_length=50),
            preserve_default=False,
        ),
    ]
