# Generated by Django 3.2.6 on 2021-08-31 09:39

from django.db import migrations, models

import inventory.models.images


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_auto_20210601_1017"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=20)),
                ("range_sku", models.CharField(max_length=20)),
                ("sku", models.CharField(max_length=20)),
                (
                    "image_file",
                    models.ImageField(
                        upload_to=inventory.models.images.product_image_path
                    ),
                ),
            ],
        ),
    ]
