# Generated by Django 2.0.2 on 2018-02-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20180227_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bay',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
