# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20171115_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingprice',
            old_name='max_wieght',
            new_name='max_weight',
        ),
        migrations.RenameField(
            model_name='shippingprice',
            old_name='min_wieght',
            new_name='min_weight',
        ),
    ]
