# Generated by Django 2.1.7 on 2019-02-26 12:08

from django.db import migrations


def clear_locations(apps, schema_editor):
    """Remove all warehouses and bays."""
    Warehouse = apps.get_model("inventory", "Warehouse")
    Bay = apps.get_model("inventory", "Bay")
    Warehouse.objects.all().delete()
    Bay.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [("inventory", "0008_auto_20190214_1550")]

    operations = [migrations.RunPython(clear_locations)]
