# Generated by Django 2.0.3 on 2018-04-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20180227_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='abriviation',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
