# Generated by Django 3.1.14 on 2022-03-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_auto_20220301_1440"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="listing_attributes",
        ),
        migrations.RemoveField(
            model_name="product",
            name="variation_options",
        ),
    ]
