# Generated by Django 4.0.1 on 2022-02-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_productimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
