# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20171116_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingprice',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
