# Generated by Django 2.1.7 on 2019-02-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("inventory", "0009_clear_bays_and_warehouses")]

    operations = [migrations.RemoveField(model_name="bay", name="warehouse")]
