# Generated by Django 3.1.14 on 2022-03-01 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_auto_20220301_1443"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="supplier_SKU",
            new_name="supplier_sku",
        ),
    ]
