# Generated by Django 3.1.14 on 2022-03-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_auto_20220301_1532"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagetype",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
