# Generated by Django 4.0.5 on 2022-06-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_productimagelink_baseproduct_images_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.DeleteModel(
            name='ProductRangeImage',
        ),
    ]
