# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_shippingprice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingprice',
            name='name',
            field=models.CharField(default='default', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
