# Generated by Django 4.0.5 on 2022-06-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_productimage_options_delete_productrangeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='active',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
    ]
