# Generated by Django 2.1.7 on 2019-02-26 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0011_change_location_primary_keys")]

    operations = [
        migrations.AddField(
            model_name="bay",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.Warehouse"
            ),
            preserve_default=False,
        )
    ]
