# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20171116_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingprice',
            name='max_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingprice',
            name='min_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
