# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20171116_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingprice',
            old_name='max_value',
            new_name='max_price',
        ),
        migrations.RenameField(
            model_name='shippingprice',
            old_name='min_value',
            new_name='min_price',
        ),
    ]
