# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20171116_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingprice',
            name='vat_required',
            field=models.BooleanField(default=False),
        ),
    ]
