# Generated by Django 2.1.7 on 2019-02-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0013_auto_20190226_1221")]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="abriviation",
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        )
    ]
