# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_shippingprice_vat_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cc_id', models.PositiveSmallIntegerField()),
                ('percentage', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='shippingprice',
            name='vat_required',
        ),
        migrations.AlterField(
            model_name='shippingprice',
            name='item_price',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='shippingprice',
            name='kilo_price',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingprice',
            name='max_price',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingprice',
            name='max_weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingprice',
            name='min_price',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingprice',
            name='min_weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingprice',
            name='vat_rates',
            field=models.ManyToManyField(to='inventory.VATRate'),
        ),
    ]
