# Generated by Django 2.1.7 on 2019-02-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("inventory", "0014_auto_20190226_1238")]

    operations = [
        migrations.RenameField(model_name="bay", old_name="bay_id", new_name="bay_ID"),
        migrations.RenameField(
            model_name="warehouse", old_name="warehouse_id", new_name="warehouse_ID"
        ),
    ]
