# Generated by Django 4.0.6 on 2022-07-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_productimagelink_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproduct',
            name='height_mm',
        ),
        migrations.RemoveField(
            model_name='baseproduct',
            name='length_mm',
        ),
        migrations.RemoveField(
            model_name='baseproduct',
            name='width_mm',
        ),
    ]
