# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20171120_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingprice',
            name='vat_rates',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.VATRate'),
        ),
    ]
