# Generated by Django 4.0.6 on 2022-07-07 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_baseproduct_height_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='depth',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Depth (cm)'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='height',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Height (cm)'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='width',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Width (cm)'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='barcode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='is_end_of_line',
            field=models.BooleanField(default=False, verbose_name='Is EOL'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='package_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.packagetype', verbose_name='Package Type'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='product_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.productrange', verbose_name='Product Range'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Retail Price'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='sku',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='supplier_barcode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Supplier Barcode'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='supplier_sku',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Supplier SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hs_code',
            field=models.CharField(max_length=50, verbose_name='HS Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Purchase Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.vatrate', verbose_name='VAT Rate'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_grams',
            field=models.PositiveSmallIntegerField(verbose_name='Weight (g)'),
        ),
    ]
