# Generated by Django 2.1.7 on 2019-02-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0015_auto_20190226_1443")]

    operations = [
        migrations.AlterField(
            model_name="bay",
            name="bay_ID",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="warehouse_ID",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
