# Generated by Django 4.0.6 on 2022-07-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_baseproduct_depth_baseproduct_height_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productimagelink',
            unique_together={('product', 'image')},
        ),
    ]
