# Generated by Django 4.0.6 on 2022-07-19 10:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_productimagelink_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagelink',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_image_links', to='inventory.productimage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimagelink',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_image_links', to='inventory.baseproduct'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductRangeImageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_range_image_links', to='inventory.productimage')),
                ('product_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_range_image_links', to='inventory.productrange')),
            ],
            options={
                'verbose_name': 'Product Range Image Link',
                'verbose_name_plural': 'Product Range Image Links',
                'ordering': ('position',),
                'unique_together': {('product_range', 'image')},
            },
        ),
    ]
