# Generated by Django 2.1.7 on 2019-03-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0017_productrange")]

    operations = [
        migrations.AlterField(
            model_name="productrange",
            name="range_ID",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        )
    ]
