# Generated by Django 4.0.6 on 2022-07-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_productimagelink_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrange',
            name='images',
            field=models.ManyToManyField(related_name='image_product_ranges', through='inventory.ProductRangeImageLink', to='inventory.productimage'),
        ),
    ]
