# Generated by Django 2.1.7 on 2019-03-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("inventory", "0018_auto_20190313_1124")]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="product_option_ID",
            new_name="product_option_value_ID",
        ),
        migrations.RenameField(
            model_name="internationalshipping",
            old_name="product_option_ID",
            new_name="product_option_value_ID",
        ),
        migrations.RenameField(
            model_name="packagetype",
            old_name="product_option_ID",
            new_name="product_option_value_ID",
        ),
        migrations.RenameField(
            model_name="supplier",
            old_name="product_option_ID",
            new_name="product_option_value_ID",
        ),
    ]
