# Generated by Django 2.1.7 on 2019-03-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0019_auto_20190314_1643")]

    operations = [
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, db_index=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("product_option_ID", models.CharField(max_length=20, unique=True)),
                ("inactive", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Product Option",
                "verbose_name_plural": "Product Options",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        )
    ]
