# Generated by Django 4.1.3 on 2022-11-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0020_delete_productexport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseproduct",
            name="latest_stock_change",
        ),
    ]
