# Generated by Django 2.1.7 on 2019-03-18 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0020_productoption")]

    operations = [
        migrations.CreateModel(
            name="ProductOptionValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_option_value_ID",
                    models.CharField(max_length=20, unique=True),
                ),
                ("value", models.CharField(max_length=255)),
                (
                    "product_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.ProductOption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Option Value",
                "verbose_name_plural": "Product Option Values",
                "abstract": False,
            },
        )
    ]
