# Generated by Django 4.2.3 on 2023-07-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0021_remove_baseproduct_latest_stock_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseproduct",
            name="additional_suppliers",
            field=models.ManyToManyField(
                blank=True,
                related_name="additional_products",
                to="inventory.supplier",
                verbose_name="Additional Suppliers",
            ),
        ),
    ]
