# Generated by Django 4.2.4 on 2023-08-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0022_baseproduct_additional_suppliers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baseproduct",
            options={
                "base_manager_name": "objects",
                "ordering": (
                    "product_range",
                    "is_archived",
                    "is_end_of_line",
                    "range_order",
                ),
                "verbose_name": "Base Product",
                "verbose_name_plural": "Base Products",
            },
        ),
        migrations.RemoveField(
            model_name="productrange",
            name="hidden",
        ),
        migrations.RemoveField(
            model_name="productrange",
            name="is_end_of_line",
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="Is Archived"),
        ),
    ]
