# Generated by Django 2.1.7 on 2019-03-19 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0022_brand_manufacturer")]

    operations = [
        migrations.CreateModel(
            name="VATRate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, db_index=True)),
                ("VAT_rate_ID", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "percentage",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "VAT Rate",
                "verbose_name_plural": "VAT Rates",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        )
    ]
