# Generated by Django 2.1.7 on 2019-03-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("inventory", "0023_vatrate")]

    operations = [
        migrations.AlterUniqueTogether(
            name="productoptionvalue", unique_together={("product_option", "value")}
        )
    ]
