# Generated by Django 4.2.6 on 2023-10-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0023_alter_baseproduct_options_remove_productrange_hidden_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="blacklisted",
            field=models.BooleanField(default=False),
        ),
    ]
