# Generated by Django 2.1.7 on 2019-03-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0024_auto_20190321_1048")]

    operations = [
        migrations.AddField(
            model_name="productrange",
            name="variation_options",
            field=models.ManyToManyField(blank=True, to="inventory.ProductOption"),
        )
    ]
