# Generated by Django 2.1.7 on 2019-03-25 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0025_productrange_variation_options")]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_ID",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("SKU", models.CharField(db_index=True, max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "supplier_SKU",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("barcode", models.CharField(max_length=20)),
                ("purchase_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "retail_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("description", models.TextField()),
                ("weight_grams", models.PositiveSmallIntegerField()),
                ("length_mm", models.PositiveSmallIntegerField()),
                ("height_mm", models.PositiveSmallIntegerField()),
                ("width_mm", models.PositiveSmallIntegerField()),
                ("amazon_search_terms", models.TextField()),
                ("amazon_bullet_points", models.TextField()),
                ("multipack", models.BooleanField(default=False)),
                ("end_of_line", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("creating", "Creating"),
                            ("updating", "Updating"),
                            ("error", "Error"),
                        ],
                        default="creating",
                        max_length=20,
                    ),
                ),
                ("date_created", models.DateField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "VAT_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.VATRate",
                    ),
                ),
                ("bays", models.ManyToManyField(blank=True, to="inventory.Bay")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.Brand",
                    ),
                ),
                (
                    "international_shipping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.InternationalShipping",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.Manufacturer",
                    ),
                ),
                (
                    "package_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.PackageType",
                    ),
                ),
                (
                    "product_options",
                    models.ManyToManyField(
                        blank=True, to="inventory.ProductOptionValue"
                    ),
                ),
                (
                    "product_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.ProductRange",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.Supplier",
                    ),
                ),
            ],
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        )
    ]
