# Generated by Django 4.2.7 on 2023-11-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0025_supplier_last_ordered_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_flammable",
            field=models.BooleanField(default=False, verbose_name="Is Flammable"),
        ),
    ]
