# Generated by Django 2.2 on 2019-04-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0026_product")]

    operations = [
        migrations.AddField(
            model_name="productrange",
            name="amazon_bullet_points",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="productrange",
            name="amazon_search_terms",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="productrange",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
