# Generated by Django 2.2 on 2019-04-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("inventory", "0027_auto_20190409_0921")]

    operations = [
        migrations.RemoveField(model_name="product", name="amazon_bullet_points"),
        migrations.RemoveField(model_name="product", name="amazon_search_terms"),
        migrations.RemoveField(model_name="product", name="description"),
    ]
