# Generated by Django 2.2 on 2019-04-09 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0028_auto_20190409_0939")]

    operations = [
        migrations.RemoveField(model_name="productrange", name="variation_options"),
        migrations.CreateModel(
            name="ProductRangeVariableOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.ProductOption",
                    ),
                ),
                (
                    "product_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.ProductRange",
                    ),
                ),
            ],
            options={"ordering": ("product_option__ordering",)},
        ),
    ]
