# Generated by Django 5.1.1 on 2024-09-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0029_packingrequirement_baseproduct_packing_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseproduct",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="productrange",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
