# Generated by Django 2.2 on 2019-04-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("inventory", "0030_productrange_variation_options")]

    operations = [
        migrations.RenameModel(
            old_name="ProductRangeVariableOptions",
            new_name="ProductRangeVariableOption",
        ),
        migrations.AlterModelOptions(
            name="productrangevariableoption",
            options={
                "ordering": ("product_option__ordering",),
                "verbose_name": "ProductRangeVariableOption",
                "verbose_name_plural": "ProductRangeVariableOptions",
            },
        ),
        migrations.AlterUniqueTogether(
            name="productrangevariableoption",
            unique_together={("product_range", "product_option")},
        ),
    ]
