# Generated by Django 2.2 on 2019-04-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0032_auto_20190409_1445")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_options",
            field=models.ManyToManyField(
                blank=True,
                through="inventory.ProductOptionValueLink",
                to="inventory.ProductOptionValue",
            ),
        )
    ]
