# Generated by Django 2.2 on 2019-04-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("inventory", "0033_product_product_options")]

    operations = [
        migrations.AlterModelOptions(
            name="productoptionvaluelink",
            options={
                "ordering": ("product_option_value__product_option",),
                "verbose_name": "ProductRangeVariableOption",
                "verbose_name_plural": "ProductRangeVariableOptions",
            },
        ),
        migrations.AlterModelOptions(
            name="productrangevariableoption",
            options={
                "ordering": ("product_option",),
                "verbose_name": "ProductRangeVariableOption",
                "verbose_name_plural": "ProductRangeVariableOptions",
            },
        ),
    ]
