# Generated by Django 2.2 on 2019-04-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("inventory", "0034_auto_20190409_1459")]

    operations = [
        migrations.AlterModelOptions(
            name="productoptionvaluelink",
            options={
                "ordering": ("product_option_value__product_option",),
                "verbose_name": "ProductOptionValueLink",
                "verbose_name_plural": "ProductOptionValueLinks",
            },
        )
    ]
