# Generated by Django 2.2 on 2019-04-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0035_auto_20190409_1506")]

    operations = [
        migrations.RenameModel(
            old_name="ProductRangeVariableOption",
            new_name="ProductRangeSelectedOptions",
        ),
        migrations.RemoveField(model_name="productrange", name="variation_options"),
        migrations.AddField(
            model_name="productrange",
            name="product_options",
            field=models.ManyToManyField(
                blank=True,
                through="inventory.ProductRangeSelectedOptions",
                to="inventory.ProductOption",
            ),
        ),
    ]
