# Generated by Django 2.2 on 2019-04-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0036_auto_20190410_1313")]

    operations = [
        migrations.AddField(
            model_name="productrangeselectedoptions",
            name="variation",
            field=models.BooleanField(default=True),
            preserve_default=False,
        )
    ]
