# Generated by Django 2.2 on 2019-04-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("inventory", "0038_auto_20190410_1320")]

    operations = [migrations.RemoveField(model_name="product", name="name")]
