# Generated by Django 2.2 on 2019-04-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0039_remove_product_name")]

    operations = [
        migrations.AddField(
            model_name="packagetype",
            name="large_letter_compatible",
            field=models.BooleanField(default=False),
            preserve_default=False,
        )
    ]
