# Generated by Django 2.2 on 2019-04-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0040_packagetype_large_letter_compatible")]

    operations = [
        migrations.AlterModelOptions(
            name="bay",
            options={
                "ordering": ("-is_default", "name"),
                "verbose_name": "Bay",
                "verbose_name_plural": "Bays",
            },
        ),
        migrations.AddField(
            model_name="bay",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="bay",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_default=True),
                fields=("warehouse",),
                name="single_default_bay_per_warehouse",
            ),
        ),
    ]
