# Generated by Django 2.2 on 2019-04-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0041_auto_20190417_1322")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="range_order",
            field=models.PositiveSmallIntegerField(default=0),
        )
    ]
