# Generated by Django 2.2 on 2019-04-30 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0042_product_range_order")]

    operations = [
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, db_index=True)),
                (
                    "product_option_value_ID",
                    models.CharField(max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("inactive", models.BooleanField(default=False)),
                ("readable_name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Gender",
                "verbose_name_plural": "Genders",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.Gender",
            ),
        ),
    ]
