# Generated by Django 2.2.1 on 2019-05-16 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0043_auto_20190430_1236")]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_ID",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("filename", models.CharField(max_length=200)),
                ("URL", models.URLField()),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ("position",),
            },
        ),
        migrations.DeleteModel(name="STCAdminImage"),
    ]
