# Generated by Django 2.2.1 on 2019-06-06 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0044_auto_20190516_1417")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.Gender",
            ),
        )
    ]
