# Generated by Django 2.2.3 on 2019-07-04 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0045_auto_20190606_1045")]

    operations = [
        migrations.CreateModel(
            name="PartialProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_ID", models.CharField(max_length=50, null=True, unique=True)),
                ("SKU", models.CharField(max_length=255, null=True, unique=True)),
                (
                    "supplier_SKU",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("barcode", models.CharField(max_length=20, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "retail_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("weight_grams", models.PositiveSmallIntegerField(null=True)),
                ("length_mm", models.PositiveSmallIntegerField(null=True)),
                ("height_mm", models.PositiveSmallIntegerField(null=True)),
                ("width_mm", models.PositiveSmallIntegerField(null=True)),
                ("multipack", models.BooleanField(default=False)),
                ("end_of_line", models.BooleanField(default=False)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("range_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "VAT_rate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.VATRate",
                    ),
                ),
                ("bays", models.ManyToManyField(blank=True, to="inventory.Bay")),
                (
                    "brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.Brand",
                    ),
                ),
                (
                    "gender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.Gender",
                    ),
                ),
                (
                    "international_shipping",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.InternationalShipping",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.Manufacturer",
                    ),
                ),
                (
                    "original_product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.Product",
                    ),
                ),
                (
                    "package_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.PackageType",
                    ),
                ),
            ],
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.CreateModel(
            name="PartialProductRange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("range_ID", models.CharField(max_length=50, null=True, unique=True)),
                (
                    "SKU",
                    models.CharField(
                        db_index=True, max_length=15, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("amazon_search_terms", models.TextField(blank=True, default="")),
                ("amazon_bullet_points", models.TextField(blank=True, default="")),
                ("end_of_line", models.BooleanField(default=False)),
                ("hidden", models.BooleanField(default=False)),
                ("date_created", models.DateField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.Department",
                    ),
                ),
                (
                    "original_range",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.ProductRange",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partial Product Range",
                "verbose_name_plural": "Partial Product Ranges",
            },
        ),
        migrations.CreateModel(
            name="PartialProductRangeSelectedOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variation", models.BooleanField()),
                (
                    "product_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.ProductOption",
                    ),
                ),
                (
                    "product_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.PartialProductRange",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partial Product Range Selected Option",
                "verbose_name_plural": "Partial Product Range Selected Options",
                "ordering": ("product_option",),
                "unique_together": {("product_range", "product_option")},
            },
        ),
        migrations.AddField(
            model_name="partialproductrange",
            name="product_options",
            field=models.ManyToManyField(
                blank=True,
                through="inventory.PartialProductRangeSelectedOption",
                to="inventory.ProductOption",
            ),
        ),
        migrations.CreateModel(
            name="PartialProductOptionValueLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.PartialProduct",
                    ),
                ),
                (
                    "product_option_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.ProductOptionValue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partial Product Option Value Link",
                "verbose_name_plural": "Partial Product Option Value Links",
                "ordering": ("product_option_value__product_option",),
                "unique_together": {("product", "product_option_value")},
            },
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="product_options",
            field=models.ManyToManyField(
                blank=True,
                through="inventory.PartialProductOptionValueLink",
                to="inventory.ProductOptionValue",
            ),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="product_range",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.PartialProductRange",
            ),
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.Supplier",
            ),
        ),
    ]
