# Generated by Django 2.2.3 on 2019-07-04 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0048_productedit")]

    operations = [
        migrations.AlterField(
            model_name="productedit",
            name="partial_product_range",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.PartialProductRange",
            ),
        ),
        migrations.AlterField(
            model_name="productedit",
            name="product_range",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.ProductRange"
            ),
        ),
    ]
