# Generated by Django 2.2.3 on 2019-07-04 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0049_auto_20190704_1157")]

    operations = [
        migrations.AddField(
            model_name="partialproduct",
            name="date_created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="partialproduct",
            name="status",
            field=models.CharField(
                choices=[
                    ("complete", "Complete"),
                    ("creating", "Creating"),
                    ("updating", "Updating"),
                    ("error", "Error"),
                ],
                default="creating",
                max_length=20,
            ),
        ),
    ]
