# Generated by Django 2.2.2 on 2019-07-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("inventory", "0050_auto_20190704_1301")]

    operations = [
        migrations.AlterModelOptions(
            name="partialproduct",
            options={
                "verbose_name": "Partial Product",
                "verbose_name_plural": "Partial Products",
            },
        )
    ]
