# Generated by Django 2.2.2 on 2019-07-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("inventory", "0051_auto_20190710_1407")]

    operations = [
        migrations.RemoveField(model_name="partialproductrange", name="date_created")
    ]
