# Generated by Django 2.2.2 on 2019-07-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0052_remove_partialproductrange_date_created")]

    operations = [
        migrations.AddField(
            model_name="productedit",
            name="product_option_values",
            field=models.ManyToManyField(to="inventory.ProductOptionValue"),
        )
    ]
