# Generated by Django 2.2.2 on 2019-07-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0053_productedit_product_option_values")]

    operations = [
        migrations.AddField(
            model_name="partialproduct",
            name="pre_existing",
            field=models.BooleanField(default=False),
        )
    ]
