# Generated by Django 2.2.2 on 2019-08-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0054_partialproduct_pre_existing")]

    operations = [
        migrations.AddField(
            model_name="partialproductrangeselectedoption",
            name="pre_existing",
            field=models.BooleanField(default=False),
        )
    ]
