# Generated by Django 2.0.6 on 2018-06-21 11:04

from django.db import migrations, models


def get_group_names():
    from django.apps import apps
    return [
        name for name, app in apps.app_configs.items()
        if hasattr(app, 'create_group') and app.create_group is True
    ]


def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for name in get_group_names():
        Group.objects.get_or_create(name=name)


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=get_group_names()).delete()


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(apply_migration, revert_migration)]
