# Generated by Django 3.0 on 2019-12-09 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudCommerceUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=10, unique=True)),
                ("first_name", models.CharField(max_length=50)),
                ("second_name", models.CharField(max_length=50)),
                ("hidden", models.BooleanField(default=False)),
                (
                    "stcadmin_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_stcadmin_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cloud Commerce User",
                "verbose_name_plural": "Cloud Commerce Users",
            },
        )
    ]
