# Generated by Django 4.0.5 on 2022-06-16 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_auto_20210601_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudcommerceuser',
            name='stcadmin_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cloud_commerce_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
