# Generated by Django 4.0.5 on 2022-06-20 09:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0033_order_packed_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0006_alter_cloudcommerceuser_stcadmin_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CloudCommerceUser",
            new_name="Staff",
        ),
    ]
