# Generated by Django 4.0.5 on 2022-06-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_staff_stcadmin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user_id',
        ),
        migrations.AddField(
            model_name='staff',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
