# Generated by Django 4.0.5 on 2022-06-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_staff_user_id_staff_email_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
    ]
