# Generated by Django 4.2.5 on 2023-09-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_alter_staff_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="fba_packer",
            field=models.BooleanField(default=False),
        ),
    ]
