# Generated by Django 5.1 on 2024-08-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_staff_fba_packer"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="can_clock_in",
            field=models.BooleanField(default=False),
        ),
    ]
