# Generated by Django 3.0.3 on 2020-03-02 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("english", models.TextField(unique=True)),
                ("french", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="FnacProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("sku", models.CharField(max_length=255, unique=True)),
                ("barcode", models.CharField(max_length=15)),
                ("description", models.TextField()),
                ("price", models.PositiveIntegerField(blank=True, null=True)),
                ("brand", models.CharField(max_length=255)),
                ("colour", models.CharField(max_length=255)),
                ("stock_level", models.IntegerField()),
                ("do_not_create", models.BooleanField(default=False)),
                ("created", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("colour", models.CharField(max_length=255)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fnac.FnacProduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FnacRange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("sku", models.CharField(max_length=255, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fnac.Category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fnacproduct",
            name="fnac_range",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fnac.FnacRange"
            ),
        ),
        migrations.AddField(
            model_name="fnacproduct",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fnac.Size",
            ),
        ),
    ]
