# Generated by Django 3.0.3 on 2020-03-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("fnac", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="fnacproduct",
            name="colour",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="translation",
            name="colour",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
