# Generated by Django 3.0.3 on 2020-03-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("fnac", "0002_auto_20200303_1335")]

    operations = [
        migrations.AlterField(
            model_name="category", name="name", field=models.CharField(max_length=255)
        )
    ]
