# Generated by Django 3.0.3 on 2020-03-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fnac", "0002_auto_20200312_1143"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
            ],
        ),
    ]
