# Generated by Django 3.0.4 on 2020-04-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fnac", "0004_auto_20200324_1129"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="requires_colour",
            field=models.BooleanField(default=False),
        ),
    ]
