# Generated by Django 3.0.5 on 2020-04-21 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_delete_stcadminimage"),
        ("fnac", "0006_missinginformationexport"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryImport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("error", "Error"),
                            ("in_progress", "In Progress"),
                        ],
                        default="in_progress",
                        max_length=15,
                    ),
                ),
                (
                    "export",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.ProductExport",
                    ),
                ),
            ],
        ),
    ]
