# Generated by Django 3.0.6 on 2020-05-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fnac", "0010_missinginformationimport"),
    ]

    operations = [
        migrations.CreateModel(
            name="MiraklProductImport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("error", "Error"),
                            ("in_progress", "In Progress"),
                        ],
                        default="in_progress",
                        max_length=15,
                    ),
                ),
                (
                    "import_file",
                    models.FileField(
                        null=True, upload_to="fnac/mirakl_product_exports/"
                    ),
                ),
            ],
        ),
    ]
