# Generated by Django 3.0.6 on 2020-05-12 11:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fnac", "0011_miraklproductimport"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationUpdate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("error", "Error"),
                            ("in_progress", "In Progress"),
                        ],
                        default="in_progress",
                        max_length=15,
                    ),
                ),
                ("translation_text", models.TextField()),
                (
                    "errors",
                    django.contrib.postgres.fields.jsonb.JSONField(default=list),
                ),
            ],
        ),
    ]
