# Generated by Django 3.0.7 on 2020-06-15 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_delete_stcadminimage"),
        ("fnac", "0012_translationupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="fnacproduct",
            name="supplier",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.Supplier",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="FnacConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ignored_suppliers",
                    models.ManyToManyField(blank=True, to="inventory.Supplier"),
                ),
            ],
            options={"abstract": False},
        ),
    ]
