# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('use', models.TextField()),
            ],
        ),
    ]
