# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0002_othertag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['tag']},
        ),
        migrations.AlterModelOptions(
            name='othertag',
            options={'ordering': ['tag']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['tag']},
        ),
    ]
