# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-01 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudCommerceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10, unique=True)),
                ('date_created', models.DateTimeField()),
                ('customer_id', models.CharField(max_length=10)),
                ('trigger_id', models.CharField(max_length=10)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField()),
                ('customer_order_dispatch_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CloudCommerceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('feedback_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print_audit.CloudCommerceUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print_audit.Feedback')),
            ],
        ),
        migrations.AddField(
            model_name='cloudcommerceorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print_audit.CloudCommerceUser'),
        ),
    ]
