# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-01 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('print_audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='feedback_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print_audit.Feedback'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print_audit.CloudCommerceUser'),
        ),
    ]
