# Generated by Django 2.2.1 on 2019-06-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("print_audit", "0001_initial_squashed_0013_auto_20180704_1001")]

    operations = [
        migrations.AddField(
            model_name="cloudcommerceuser",
            name="first_name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cloudcommerceuser",
            name="second_name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
