# Generated by Django 3.0 on 2019-12-09 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_cloudcommerceuser"),
        ("print_audit", "0002_auto_20190605_1415"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breakage",
            name="packer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.CloudCommerceUser"
            ),
        ),
        migrations.AlterField(
            model_name="cloudcommerceorder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.CloudCommerceUser"
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.CloudCommerceUser"
            ),
        ),
        migrations.DeleteModel(name="CloudCommerceUser"),
    ]
