# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-01 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_audit', '0002_auto_20170801_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='order_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
