# Generated by Django 3.0 on 2019-12-12 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_cloudcommerceuser"),
        ("print_audit", "0003_auto_20191209_1132"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="feedback_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="old_feedback_type",
                to="print_audit.Feedback",
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="old_user",
                to="home.CloudCommerceUser",
            ),
        ),
    ]
