# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-02 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('print_audit', '0003_auto_20170801_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
