# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-29 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('print_audit', '0004_auto_20170802_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudcommerceuser',
            name='cc_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
