# Generated by Django 3.0 on 2019-12-18 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_cloudcommerceuser"),
        ("print_audit", "0005_auto_20191212_1526"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breakage",
            name="packer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="old_breakage",
                to="home.CloudCommerceUser",
            ),
        )
    ]
