# Generated by Django 3.0.2 on 2020-01-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("print_audit", "0006_auto_20191218_1623")]

    operations = [
        migrations.RemoveField(model_name="cloudcommerceorder", name="user"),
        migrations.DeleteModel(name="Breakage"),
        migrations.DeleteModel(name="CloudCommerceOrder"),
    ]
