# Generated by Django 2.0.3 on 2018-05-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_audit', '0007_feedback_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(upload_to='feedback'),
        ),
    ]
