# Generated by Django 2.0.5 on 2018-05-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print_audit', '0008_auto_20180503_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudcommerceorder',
            options={'verbose_name': 'Cloud Commerce Order', 'verbose_name_plural': 'Cloud Commerce Orders'},
        ),
        migrations.AlterModelOptions(
            name='cloudcommerceuser',
            options={'verbose_name': 'Cloud Commerce User', 'verbose_name_plural': 'Cloud Commerce Users'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback'},
        ),
        migrations.AlterModelOptions(
            name='userfeedback',
            options={'verbose_name': 'User Feedback', 'verbose_name_plural': 'User Feedback'},
        ),
    ]
