# Generated by Django 2.0.5 on 2018-05-15 11:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('print_audit', '0009_auto_20180514_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=10)),
                ('order_id', models.CharField(max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('packer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print_audit.CloudCommerceUser')),
            ],
            options={
                'verbose_name': 'Breakage',
                'verbose_name_plural': 'Breakages',
                'ordering': ('timestamp',),
            },
        ),
    ]
