# Generated by Django 2.0.5 on 2018-05-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_audit', '0010_breakage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakage',
            name='product_sku',
            field=models.CharField(max_length=20),
        ),
    ]
