# Generated by Django 2.0.5 on 2018-05-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_audit', '0011_auto_20180515_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudcommerceuser',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
