# Generated by Django 2.0.7 on 2018-07-04 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('print_audit', '0012_cloudcommerceuser_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
