# Generated by Django 2.0.1 on 2018-01-25 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spring_manifest', '0025_auto_20180122_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(unique=True)),
                ('weight', models.PositiveIntegerField()),
                ('vat', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.PositiveIntegerField()),
                ('purchase_price', models.PositiveIntegerField()),
                ('item_count', models.PositiveIntegerField()),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spring_manifest.CloudCommerceCountryID')),
            ],
        ),
    ]
