# Generated by Django 2.0.7 on 2018-07-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_loss', '0001_initial_squashed_0009_auto_20180514_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_recieved',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='dispatch_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='postage_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_service',
            field=models.CharField(max_length=250),
        ),
    ]
