# Generated by Django 2.0.1 on 2018-01-25 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profit_loss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_recieved',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='dispatch_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
