# Generated by Django 2.2.6 on 2019-10-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profit_loss", "0002_auto_20180731_1249")]

    operations = [
        migrations.AddField(
            model_name="order", name="error", field=models.BooleanField(default=False)
        ),
        migrations.AlterField(
            model_name="order",
            name="item_count",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="postage_price",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="purchase_price",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_service",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("error", True), ("postage_price__isnull", False), _connector="OR"
                ),
                name="postage_price_not_null_unless_error",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("error", True), ("item_count__isnull", False), _connector="OR"
                ),
                name="item_count_not_null_unless_error",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("error", True),
                    ("shipping_service__isnull", False),
                    _connector="OR",
                ),
                name="shipping_service_not_null_unless_error",
            ),
        ),
    ]
