# Generated by Django 2.0.1 on 2018-01-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profit_loss', '0002_auto_20180125_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='vat',
            new_name='vat_rate',
        ),
    ]
