# Generated by Django 2.0.1 on 2018-01-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_loss', '0003_auto_20180125_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postage_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
