# Generated by Django 2.0.1 on 2018-01-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_loss', '0004_order_postage_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_service',
            field=models.CharField(default='none', max_length=250),
            preserve_default=False,
        ),
    ]
