# Generated by Django 2.0.1 on 2018-01-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_loss', '0005_order_shipping_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
