# Generated by Django 2.0.1 on 2018-01-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_loss', '0006_order_customer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-dispatch_date']},
        ),
        migrations.AddField(
            model_name='order',
            name='department',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
