# Generated by Django 2.0.1 on 2018-02-19 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profit_loss', '0007_auto_20180131_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('range_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('name', models.TextField()),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profit_loss.Order')),
            ],
        ),
    ]
