# Generated by Django 2.0.5 on 2018-05-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profit_loss', '0008_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-dispatch_date'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
