# Generated by Django 5.1.6 on 2025-03-10 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_staff_can_clock_in"),
        ("logs", "0002_rename_work_worklog_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="FBALogUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "staff_member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="is_on_fba_log",
                        to="home.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Log User",
                "verbose_name_plural": "Work Log Users",
            },
        ),
    ]
