# Generated by Django 4.2.4 on 2023-08-15 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("channels", "0001_initial"),
        ("channels", "0002_alter_shopifytag_name"),
        ("channels", "0003_shopifycollection_alter_shopifylisting_tags_and_more"),
    ]

    initial = True

    dependencies = [
        ("inventory", "0019_productrange_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopifyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopifyListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("product_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "product_range",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopify_listing",
                        to="inventory.productrange",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shopify Listing",
                "verbose_name_plural": "Shopify Listings",
            },
        ),
        migrations.CreateModel(
            name="ShopifyTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Shopify Tag",
                "verbose_name_plural": "Shopify Tags",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ShopifyVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("variant_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "inventory_item_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="channels.shopifylisting",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopify_variation",
                        to="inventory.baseproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shopify Variation",
                "verbose_name_plural": "Shopify Variations",
            },
        ),
        migrations.CreateModel(
            name="ShopifyUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("Create Product", "Create Product"),
                            ("Update Product", "Update Product"),
                            ("Retrieve Product", "Retrieve Product"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.BooleanField(default=False)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_records",
                        to="channels.shopifylisting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shopify Update",
                "verbose_name_plural": "Shopify Updates",
            },
        ),
        migrations.CreateModel(
            name="ShopifyCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("collection_id", models.PositiveBigIntegerField()),
            ],
            options={
                "verbose_name": "Shopify Collection",
                "verbose_name_plural": "Shopify Collections",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="shopifylisting",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="shopify_listings", to="channels.shopifytag"
            ),
        ),
        migrations.AddField(
            model_name="shopifylisting",
            name="collections",
            field=models.ManyToManyField(
                blank=True,
                related_name="shopify_listings",
                to="channels.shopifycollection",
            ),
        ),
    ]
