# Generated by Django 4.1 on 2022-08-09 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0019_productrange_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopifyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopifyListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("product_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "product_range",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopify_listing",
                        to="inventory.productrange",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShopifyTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ShopifyVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("variant_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "inventory_item_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="channels.shopifylisting",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopify_variation",
                        to="inventory.baseproduct",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shopifylisting",
            name="tags",
            field=models.ManyToManyField(blank=True, to="channels.shopifytag"),
        ),
    ]
