# Generated by Django 3.1.6 on 2021-02-03 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("channel_id", models.CharField(max_length=10)),
                ("inactive", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CreatedOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=20)),
                ("order_id", models.CharField(max_length=20)),
                ("billing_address_id", models.CharField(max_length=20)),
                ("delivery_address_id", models.CharField(max_length=20)),
                ("invoice_id", models.CharField(max_length=20)),
                ("price", models.FloatField()),
                ("shipping_price", models.FloatField()),
                ("total_to_pay", models.FloatField()),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="channels.channel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DefaultContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "Default Order Contact",
            },
        ),
        migrations.CreateModel(
            name="CreatedOrderProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=20)),
                ("quantity", models.PositiveSmallIntegerField()),
                ("item_price", models.FloatField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="channels.createdorder",
                    ),
                ),
            ],
        ),
    ]
