# Generated by Django 4.0.6 on 2022-07-26 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_productrange_images'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShopifyVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_variation', to='inventory.baseproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ShopifyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('product_range', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_listing', to='inventory.productrange')),
                ('tags', models.ManyToManyField(to='channels.shopifytag')),
            ],
        ),
    ]
