# Generated by Django 4.1.1 on 2022-09-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0002_alter_shopifytag_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopifyCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("collection_id", models.PositiveBigIntegerField()),
            ],
            options={
                "verbose_name": "Shopify Collection",
                "verbose_name_plural": "Shopify Collections",
                "ordering": ("name",),
            },
        ),
        migrations.AlterField(
            model_name="shopifylisting",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="shopify_listings", to="channels.shopifytag"
            ),
        ),
        migrations.AddField(
            model_name="shopifylisting",
            name="collections",
            field=models.ManyToManyField(
                blank=True,
                related_name="shopify_listings",
                to="channels.shopifycollection",
            ),
        ),
    ]
