# Generated by Django 4.0.6 on 2022-07-26 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_shopifytag_shopifyvariation_shopifylisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyvariation',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='channels.shopifylisting'),
            preserve_default=False,
        ),
    ]
