# Generated by Django 5.0.1 on 2024-01-03 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "channels",
            "0001_squashed_0003_shopifycollection_alter_shopifylisting_tags_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopifyupdate",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
