# Generated by Django 3.2.5 on 2021-08-09 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0003_auto_20210601_1017"),
    ]

    operations = [
        migrations.CreateModel(
            name="WishBulkFulfilmentExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                            ("errored", "Errored"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "download_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="channels/wish/wish_fulfilment_files",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="wishorder",
            name="fulfiled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wishorder",
            name="fulfilment_export",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="channels.wishbulkfulfilmentexport",
            ),
        ),
    ]
