# Generated by Django 4.0.6 on 2022-08-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_shopifyvariation_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifylisting',
            name='product_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopifyvariation',
            name='inventory_item_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopifyvariation',
            name='variant_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopifylisting',
            name='tags',
            field=models.ManyToManyField(blank=True, to='channels.shopifytag'),
        ),
    ]
