# Generated by Django 4.0.2 on 2022-02-09 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0006_shopifyimport_shopifyorder"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopifyFulfillmentError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("error", models.TextField(blank=True)),
                (
                    "shopify_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="channels.shopifyorder",
                    ),
                ),
            ],
        ),
    ]
