# Generated by Django 4.0.2 on 2022-02-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0007_shopifyfulfillmenterror"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shopifyorder",
            old_name="fulfiled",
            new_name="fulfilled",
        ),
    ]
