# Generated by Django 4.0.3 on 2022-03-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0008_rename_fulfiled_shopifyorder_fulfilled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createdorder',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='createdorderproduct',
            name='order',
        ),
        migrations.DeleteModel(
            name='DefaultContact',
        ),
        migrations.DeleteModel(
            name='ShopifyConfig',
        ),
        migrations.RemoveField(
            model_name='shopifyfulfillmenterror',
            name='shopify_order',
        ),
        migrations.RemoveField(
            model_name='shopifyorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shopifyorder',
            name='shopify_import',
        ),
        migrations.RemoveField(
            model_name='wishorder',
            name='fulfilment_export',
        ),
        migrations.RemoveField(
            model_name='wishorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='wishorder',
            name='wish_import',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='CreatedOrder',
        ),
        migrations.DeleteModel(
            name='CreatedOrderProduct',
        ),
        migrations.DeleteModel(
            name='ShopifyFulfillmentError',
        ),
        migrations.DeleteModel(
            name='ShopifyOrder',
        ),
        migrations.DeleteModel(
            name='WishBulkFulfilmentExport',
        ),
        migrations.DeleteModel(
            name='WishImport',
        ),
        migrations.DeleteModel(
            name='WishOrder',
        ),
    ]
