# Generated by Django 3.2.7 on 2021-09-23 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial_squashed_0023_channel_include_vat"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackedPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scurri_id", models.CharField(max_length=255)),
                ("tracking_number", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Tracked Package",
                "verbose_name_plural": "Tracked Packages",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TrackingCarrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255)),
                ("tracking_number_match", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Tracking Carrier",
                "verbose_name_plural": "Tracking Carriers",
            },
        ),
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATTEMPTED_DELIVERY", "ATTEMPTED_DELIVERY"),
                            ("UNKNOWN", "UNKNOWN"),
                            ("MANIFESTED", "MANIFESTED"),
                            ("IN_TRANSIT", "IN_TRANSIT"),
                            ("EXCEPTION", "EXCEPTION"),
                            ("DELIVERED", "DELIVERED"),
                            ("OUT_FOR_DELIVERY", "OUT_FOR_DELIVERY"),
                        ],
                        max_length=255,
                    ),
                ),
                ("carrier_code", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField()),
                ("location", models.CharField(max_length=255)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_event",
                        to="tracking.trackedpackage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracking Event",
                "verbose_name_plural": "Tracking Events",
                "ordering": ("-timestamp",),
            },
        ),
        migrations.AddField(
            model_name="trackedpackage",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tracked_package",
                to="tracking.trackingcarrier",
            ),
        ),
        migrations.AddField(
            model_name="trackedpackage",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracked_package",
                to="orders.order",
            ),
        ),
    ]
