# Generated by Django 3.2.7 on 2021-10-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackedpackage",
            name="carrier_contacted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trackedpackage",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="trackingevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("MANIFESTED", "MANIFESTED"),
                    ("IN_TRANSIT", "IN_TRANSIT"),
                    ("OUT_FOR_DELIVERY", "OUT_FOR_DELIVERY"),
                    ("ATTEMPTED_DELIVERY", "ATTEMPTED_DELIVERY"),
                    ("DELIVERED", "DELIVERED"),
                    ("EXCEPTION", "EXCEPTION"),
                    ("UNKNOWN", "UNKNOWN"),
                ],
                max_length=255,
            ),
        ),
    ]
