# Generated by Django 3.0.2 on 2020-01-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("shipping", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="symbol",
            field=models.CharField(default="$", max_length=5),
        )
    ]
