# Generated by Django 3.0.3 on 2020-02-13 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_order_shipping_service"),
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "courier_ID",
                    models.CharField(db_index=True, max_length=12, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("inactive", models.BooleanField(default=False)),
            ],
            options={"verbose_name": "Courier", "verbose_name_plural": "Couriers"},
        ),
        migrations.CreateModel(
            name="CourierService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "courier_service_ID",
                    models.CharField(db_index=True, max_length=12, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("inactive", models.BooleanField(default=False)),
                (
                    "courier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shipping.Courier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Courier Service",
                "verbose_name_plural": "Couriers Services",
            },
        ),
        migrations.CreateModel(
            name="CourierType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "courier_type_ID",
                    models.CharField(db_index=True, max_length=12, unique=True),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("inactive", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Courier Type",
                "verbose_name_plural": "Courier Types",
            },
        ),
        migrations.RemoveField(model_name="shippingrule", name="service"),
        migrations.AddField(
            model_name="provider",
            name="inactive",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="shippingrule",
            name="rule_ID",
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.DeleteModel(name="Service"),
        migrations.AddField(
            model_name="couriertype",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shipping.Provider",
            ),
        ),
        migrations.AddField(
            model_name="courier",
            name="courier_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shipping.CourierType",
            ),
        ),
        migrations.AddField(
            model_name="shippingrule",
            name="courier_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shipping.CourierService",
            ),
        ),
    ]
