# Generated by Django 3.0.3 on 2020-02-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("shipping", "0002_auto_20200213_1259")]

    operations = [
        migrations.AlterModelOptions(
            name="shippingrule",
            options={
                "ordering": ("inactive", "name"),
                "verbose_name": "Shipping Rule",
                "verbose_name_plural": "Shipping Rules",
            },
        )
    ]
