# Generated by Django 3.0.6 on 2020-05-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("shipping", "0004_auto_20200527_1129")]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("abriviation", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "ordering": ("name",),
            },
        ),
        migrations.RenameField(
            model_name="country", old_name="region", new_name="old_region"
        ),
    ]
