# Generated by Django 3.0.6 on 2020-05-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("shipping", "0006_country_region")]

    operations = [migrations.RemoveField(model_name="country", name="old_region")]
