# Generated by Django 3.0.6 on 2020-05-27 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0007_remove_country_old_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingprice",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shipping.Region",
            ),
        ),
        migrations.AlterField(
            model_name="shippingprice",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shipping.Country",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shippingprice",
            unique_together={
                ("shipping_service", "country"),
                ("shipping_service", "region"),
            },
        ),
        migrations.AddConstraint(
            model_name="shippingprice",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("country__isnull", False), ("region__isnull", True)),
                    models.Q(("country__isnull", True), ("region__isnull", False)),
                    _connector="OR",
                ),
                name="shipping_price_has_country_or_region",
            ),
        ),
    ]
