# Generated by Django 3.0.7 on 2020-06-10 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0009_auto_20200602_1109"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingrule",
            name="shipping_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shipping.ShippingService",
            ),
        ),
    ]
