# Generated by Django 3.0.7 on 2020-06-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0011_auto_20200611_1557"),
    ]

    operations = [
        migrations.RemoveField(model_name="shippingprice", name="price_type",),
    ]
