# Generated by Django 3.0.7 on 2020-06-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0012_remove_shippingprice_price_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingprice",
            name="price_per_g",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="shippingprice",
            name="item_price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="shippingprice",
            name="price_per_kg",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
