# Generated by Django 3.1.8 on 2021-04-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0015_country_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingprice",
            name="covid_surcharge",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shippingprice",
            name="fuel_surcharge",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shippingprice",
            name="item_surcharge",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
