# Generated by Django 3.2.7 on 2021-09-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0020_auto_20210818_1133"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="flag_if_not_delivered_by_days",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
