# Generated by Django 4.1.1 on 2022-09-26 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0022_remove_courier_courier_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currency",
            name="exchange_rate",
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("rate", models.DecimalField(decimal_places=3, max_digits=6)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exchange_rates",
                        to="shipping.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
                "ordering": ("-date",),
                "get_latest_by": "date",
            },
        ),
    ]
