# Generated by Django 4.1.1 on 2022-09-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0023_remove_currency_exchange_rate_exchangerate"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="exchangerate",
            unique_together={("currency", "date")},
        ),
    ]
