# Generated by Django 3.0.2 on 2020-01-28 09:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("home", "0002_cloudcommerceuser"), ("shipping", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={"verbose_name": "Channel", "verbose_name_plural": "Channels"},
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_ID",
                    models.CharField(db_index=True, max_length=12, unique=True),
                ),
                ("customer_ID", models.CharField(blank=True, max_length=12, null=True)),
                ("recieved_at", models.DateTimeField()),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled", models.BooleanField(default=False)),
                (
                    "channel_order_ID",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orders.Channel",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shipping.Country",
                    ),
                ),
                (
                    "shipping_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shipping.ShippingRule",
                    ),
                ),
                (
                    "shipping_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shipping.Service",
                    ),
                ),
            ],
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.CreateModel(
            name="OrderUpdate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Complete", "Complete"),
                            ("In Progress", "In Progress"),
                            ("Error", "Error"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="In Progress",
                        max_length=25,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Update",
                "verbose_name_plural": "Order Updates",
            },
        ),
        migrations.CreateModel(
            name="PackingRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.Order"
                    ),
                ),
                (
                    "packed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="home.CloudCommerceUser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Packing Record",
                "verbose_name_plural": "Packing Records",
            },
        ),
        migrations.CreateModel(
            name="Breakage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_sku", models.CharField(max_length=20)),
                ("order_id", models.CharField(max_length=10)),
                ("note", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "packer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.CloudCommerceUser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Breakage",
                "verbose_name_plural": "Breakages",
                "ordering": ("timestamp",),
            },
        ),
        migrations.CreateModel(
            name="ProductSale",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_ID", models.CharField(max_length=25)),
                ("quantity", models.PositiveSmallIntegerField()),
                ("price", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.Order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Sale",
                "verbose_name_plural": "Product Sales",
                "unique_together": {("order", "product_ID")},
            },
        ),
    ]
