# Generated by Django 3.0 on 2019-12-09 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0002_cloudcommerceuser"), ("orders", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="packingrecord",
            name="packed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="home.CloudCommerceUser"
            ),
        )
    ]
