# Generated by Django 3.0.3 on 2020-02-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("orders", "0001_initial")]

    operations = [migrations.RemoveField(model_name="order", name="shipping_service")]
