# Generated by Django 3.0 on 2019-12-18 16:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0002_cloudcommerceuser"), ("orders", "0002_orderupdate")]

    operations = [
        migrations.CreateModel(
            name="Breakage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_sku", models.CharField(max_length=20)),
                ("order_id", models.CharField(max_length=10)),
                ("note", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "packer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.CloudCommerceUser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Breakage",
                "verbose_name_plural": "Breakages",
                "ordering": ("timestamp",),
            },
        )
    ]
