# Generated by Django 3.0.3 on 2020-02-13 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_order_shipping_service"),
        ("shipping", "0002_auto_20200213_1259"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="courier_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shipping.CourierService",
            ),
        )
    ]
