# Generated by Django 3.0.3 on 2020-03-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0003_order_courier_service")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="can_process_order",
            field=models.BooleanField(default=True),
        )
    ]
