# Generated by Django 3.0 on 2019-12-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0003_breakage")]

    operations = [
        migrations.AlterField(
            model_name="productsale", name="price", field=models.PositiveIntegerField()
        )
    ]
