# Generated by Django 3.0.3 on 2020-03-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0004_order_can_process_order")]

    operations = [
        migrations.RemoveField(model_name="order", name="can_process_order"),
        migrations.AddField(
            model_name="order", name="ignored", field=models.BooleanField(default=False)
        ),
    ]
