# Generated by Django 3.0 on 2019-12-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0005_auto_20191219_1538")]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_ID",
            field=models.CharField(db_index=True, max_length=12, unique=True),
        )
    ]
