# Generated by Django 3.0.7 on 2020-06-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0006_auto_20200611_0952")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="priority",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="total_paid",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="total_paid_GBP",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productsale", name="name", field=models.TextField(null=True)
        ),
        migrations.AddField(
            model_name="productsale",
            name="sku",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="productsale",
            name="weight",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
