# Generated by Django 3.0.7 on 2020-06-17 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_delete_stcadminimage"),
        ("orders", "0007_auto_20200611_1108"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsale",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.Department",
            ),
        ),
        migrations.AddField(
            model_name="productsale",
            name="error",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productsale",
            name="purchase_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productsale",
            name="vat_rate",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
