# Generated by Django 3.0.7 on 2020-06-18 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0008_auto_20200617_0955")]

    operations = [
        migrations.CreateModel(
            name="OrderDetailsUpdate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Complete", "Complete"),
                            ("In Progress", "In Progress"),
                            ("Error", "Error"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="In Progress",
                        max_length=25,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Details Update",
                "verbose_name_plural": "Order Details Updates",
            },
        ),
        migrations.RenameField(
            model_name="productsale", old_name="error", new_name="details_success"
        ),
        migrations.CreateModel(
            name="OrderDetailsUpdateError",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "product_sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.ProductSale",
                    ),
                ),
                (
                    "update",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.OrderDetailsUpdate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Details Update Error",
                "verbose_name_plural": "Order Details Update Errors",
            },
        ),
    ]
