# Generated by Django 3.0.7 on 2020-06-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_auto_20200618_1255"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="postage_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="postage_price_success",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
