# Generated by Django 3.0.7 on 2020-06-29 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_delete_stcadminimage"),
        ("orders", "0010_auto_20200622_1354"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsale",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.Supplier",
            ),
        ),
    ]
