# Generated by Django 3.0.8 on 2020-07-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_auto_20200622_1354"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsale",
            name="end_of_line",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
