# Generated by Django 3.0.7 on 2020-06-30 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_productsale_supplier"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefundReason",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("auto_close", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_applied_to", models.PositiveIntegerField()),
                ("contact_contacted", models.BooleanField(default=False)),
                ("refund_accepted", models.BooleanField(blank=True, null=True)),
                ("refund_amount", models.PositiveIntegerField(blank=True, null=True)),
                ("closed", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="orders.Order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orders.ProductSale",
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orders.RefundReason",
                    ),
                ),
            ],
        ),
    ]
