# Generated by Django 3.0.8 on 2020-07-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_refund_notes"),
    ]

    operations = [
        migrations.RemoveField(model_name="demicrefund", name="refundin_ptr"),
        migrations.RemoveField(
            model_name="linkingmistakerefund", name="refundout_ptr",
        ),
        migrations.RemoveField(model_name="lostinpostrefund", name="refundin_ptr"),
        migrations.RemoveField(
            model_name="packingmistakerefund", name="refundout_ptr",
        ),
        migrations.RemoveField(model_name="productrefund", name="product"),
        migrations.RemoveField(model_name="productrefund", name="refund"),
        migrations.RemoveField(model_name="refund", name="order"),
        migrations.RemoveField(model_name="refund", name="polymorphic_ctype"),
        migrations.RemoveField(model_name="refundimage", name="product_refund"),
        migrations.RemoveField(model_name="refundimage", name="refund"),
        migrations.RemoveField(model_name="refundin", name="refund_ptr"),
        migrations.RemoveField(model_name="refundout", name="refund_ptr"),
        migrations.DeleteModel(name="BreakageRefund"),
        migrations.DeleteModel(name="DemicRefund"),
        migrations.DeleteModel(name="LinkingMistakeRefund"),
        migrations.DeleteModel(name="LostInPostRefund"),
        migrations.DeleteModel(name="PackingMistakeRefund"),
        migrations.DeleteModel(name="ProductRefund"),
        migrations.DeleteModel(name="Refund"),
        migrations.DeleteModel(name="RefundImage"),
        migrations.DeleteModel(name="RefundIn"),
        migrations.DeleteModel(name="RefundOut"),
    ]
