# Generated by Django 3.0.8 on 2020-07-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("orders", "0015_auto_20200723_1529")]

    operations = [migrations.DeleteModel(name="Breakage")]
