# Generated by Django 3.1.1 on 2020-09-02 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0016_delete_breakage")]

    operations = [
        migrations.AddField(
            model_name="refund",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        )
    ]
