# Generated by Django 3.1.1 on 2020-09-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0017_refund_created_at")]

    operations = [
        migrations.AddField(
            model_name="lostinpostrefund",
            name="returned",
            field=models.BooleanField(default=False),
        )
    ]
