# Generated by Django 3.2.3 on 2021-06-02 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0020_auto_20210601_1017"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refundimage",
            name="thumb_height",
        ),
        migrations.RemoveField(
            model_name="refundimage",
            name="thumb_width",
        ),
        migrations.RemoveField(
            model_name="refundimage",
            name="thumbnail",
        ),
    ]
