# Generated by Django 3.2.6 on 2021-08-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0021_auto_20210602_1300"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="channel_fee",
            field=models.FloatField(default=15.5),
        ),
    ]
