# Generated by Django 4.0.1 on 2022-01-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0024_alter_refund_polymorphic_ctype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refund",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
