# Generated by Django 4.0.3 on 2022-03-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0025_alter_refund_created_at"),
        ("inventory", "0003_productimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productsale",
            name="department",
        ),
    ]
