# Generated by Django 4.0.3 on 2022-03-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_remove_productsale_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetailsupdateerror',
            name='product_sale',
        ),
        migrations.RemoveField(
            model_name='orderdetailsupdateerror',
            name='update',
        ),
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
        migrations.DeleteModel(
            name='OrderDetailsUpdate',
        ),
        migrations.DeleteModel(
            name='OrderDetailsUpdateError',
        ),
    ]
