# Generated by Django 4.0.5 on 2022-06-16 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0030_alter_productsale_channel_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packed_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
