# Generated by Django 4.0.5 on 2022-06-16 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_cloudcommerceuser_stcadmin_user'),
        ('orders', '0032_remove_order_packed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packed_orders', to='home.cloudcommerceuser'),
        ),
    ]
