# Generated by Django 4.0.5 on 2022-06-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_order_packed_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackingRecord',
        ),
    ]
