# Generated by Django 4.1.1 on 2022-09-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0034_delete_packingrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_GBP",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
