# Generated by Django 4.1.1 on 2022-10-04 10:40

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0035_order_exchange_rate_order_tax_gbp"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderExportDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                            ("errored", "Errored"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "order_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveBigIntegerField(), size=None
                    ),
                ),
                (
                    "download_file",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_downloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Export Download",
                "verbose_name_plural": "Order Export Downlaods",
                "get_latest_by": "created_at",
            },
        ),
    ]
