# Generated by Django 4.2.3 on 2023-07-13 10:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_alter_staff_options"),
        ("orders", "0037_remove_contactrefund_refund_ptr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackingMistake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateField(default=django.utils.timezone.now)),
                ("order_id", models.CharField(blank=True, max_length=10, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packing_mistakes",
                        to="home.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Packing Mistake",
                "verbose_name_plural": "Packing Mistakes",
                "ordering": ("-timestamp",),
            },
        ),
    ]
