# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('min_weight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_weight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_price', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_price', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('item_price', models.PositiveSmallIntegerField()),
                ('kilo_price', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_calculator.DestinationCountry')),
                ('package_type', models.ManyToManyField(to='price_calculator.PackageType')),
            ],
        ),
        migrations.CreateModel(
            name='VATRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cc_id', models.PositiveSmallIntegerField()),
                ('percentage', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='shippingprice',
            name='vat_rates',
            field=models.ManyToManyField(blank=True, to='price_calculator.VATRate'),
        ),
    ]
