# Generated by Django 2.1.5 on 2019-01-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_calculator", "0001_initial_squashed_0006_auto_20180514_0933")
    ]

    operations = [
        migrations.AlterModelOptions(
            name="destinationcountry",
            options={
                "ordering": ("sort_order",),
                "verbose_name": "Destination Country",
                "verbose_name_plural": "Destination Countries",
            },
        ),
        migrations.AddField(
            model_name="destinationcountry",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
    ]
