# Generated by Django 2.1.5 on 2019-02-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("price_calculator", "0002_auto_20190116_1516")]

    operations = [
        migrations.CreateModel(
            name="ChannelFee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("fee_percentage", models.PositiveSmallIntegerField()),
                ("ordering", models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                "verbose_name": "Channel Fee",
                "verbose_name_plural": "Channel Fees",
                "ordering": ("ordering",),
            },
        ),
        migrations.AddField(
            model_name="destinationcountry",
            name="currency_symbol",
            field=models.CharField(default="£", max_length=1),
        ),
    ]
