# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_calculator', '0002_auto_20171120_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationcountry',
            name='currency_code',
            field=models.CharField(default='GBP', max_length=4),
        ),
    ]
