# Generated by Django 2.0.3 on 2018-05-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_calculator', '0004_destinationcountry_min_channel_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingprice',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
