# Generated by Django 2.2.4 on 2019-08-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("price_calculator", "0004_auto_20190212_1659")]

    operations = [
        migrations.AddField(
            model_name="destinationcountry",
            name="exchange_rate",
            field=models.FloatField(default=0),
            preserve_default=False,
        )
    ]
