# Generated by Django 2.0.5 on 2018-05-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_calculator', '0005_shippingprice_disabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinationcountry',
            options={'verbose_name': 'Destination Country', 'verbose_name_plural': 'Destination Countries'},
        ),
        migrations.AlterModelOptions(
            name='packagetype',
            options={'verbose_name': 'Package Type', 'verbose_name_plural': 'Package Types'},
        ),
        migrations.AlterModelOptions(
            name='shippingprice',
            options={'verbose_name': 'Shipping Price', 'verbose_name_plural': 'Shippng Prices'},
        ),
        migrations.AlterModelOptions(
            name='vatrate',
            options={'verbose_name': 'VAT Rate', 'verbose_name_plural': 'VAT Rates'},
        ),
    ]
