# Generated by Django 3.0.2 on 2020-01-15 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0001_initial"),
        ("price_calculator", "0005_destinationcountry_exchange_rate"),
    ]

    operations = [
        migrations.RemoveField(model_name="destinationcountry", name="currency_code"),
        migrations.RemoveField(model_name="destinationcountry", name="currency_symbol"),
        migrations.RemoveField(model_name="destinationcountry", name="exchange_rate"),
        migrations.RemoveField(model_name="destinationcountry", name="shipping_region"),
        migrations.AddField(
            model_name="destinationcountry",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shipping.Country",
            ),
        ),
        migrations.DeleteModel(name="ShippingRegion"),
    ]
