# Generated by Django 3.0.2 on 2020-01-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("price_calculator", "0006_auto_20200115_1108")]

    operations = [
        migrations.RemoveField(model_name="destinationcountry", name="shipping_region"),
        migrations.DeleteModel(name="ShippingRegion"),
    ]
