# Generated by Django 3.0.6 on 2020-06-02 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0009_auto_20200602_1109"),
        ("price_calculator", "0007_auto_20200528_1441"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countrychannelfee",
            name="country",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="shipping.Country"
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="package_types",
            field=models.ManyToManyField(blank=True, to="inventory.PackageType"),
        ),
    ]
