# Generated by Django 3.0.7 on 2020-06-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_calculator", "0010_auto_20200609_1216"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingmethod",
            name="channel",
            field=models.ManyToManyField(blank=True, to="price_calculator.Channel"),
        ),
    ]
