# Generated by Django 3.2.6 on 2021-08-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_calculator", "0012_auto_20210601_1017"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelfee",
            name="fee_percentage",
            field=models.FloatField(),
        ),
    ]
