# Generated by Django 4.2.4 on 2023-08-15 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0024_alter_exchangerate_unique_together"),
        (
            "price_calculator",
            "0001_squashed_0015_remove_shippingmethod_inactive_shippingmethod_active",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelfee",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="channel_fees",
                to="shipping.country",
            ),
        ),
    ]
