# Generated by Django 2.2.4 on 2019-08-12 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "range_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Range ID"
                    ),
                ),
                (
                    "product_id",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        unique=True,
                        verbose_name="Product ID",
                    ),
                ),
                ("sku", models.CharField(db_index=True, max_length=50, unique=True)),
            ],
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.CreateModel(
            name="ProductBay",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_level",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock_check.Product",
                    ),
                ),
                (
                    "bay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.Bay"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Bay",
                "verbose_name_plural": "Product Bays",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="bays",
            field=models.ManyToManyField(
                through="stock_check.ProductBay", to="inventory.Bay"
            ),
        ),
    ]
