# Generated by Django 4.0.3 on 2022-03-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock_check", "0002_auto_20210601_1017"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productbay",
            name="bay",
        ),
        migrations.RemoveField(
            model_name="productbay",
            name="product",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ProductBay",
        ),
    ]
