# Generated by Django 3.1.14 on 2022-03-01 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_check", "0002_auto_20210601_1017"),
        ("inventory", "0004_auto_20220301_1107"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productbay",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="StockCheckProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "range_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Range ID"
                    ),
                ),
                (
                    "product_id",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        unique=True,
                        verbose_name="Product ID",
                    ),
                ),
                ("sku", models.CharField(db_index=True, max_length=50, unique=True)),
                (
                    "bays",
                    models.ManyToManyField(
                        through="stock_check.ProductBay", to="inventory.Bay"
                    ),
                ),
            ],
            options={
                "verbose_name": "StockCheckProduct",
                "verbose_name_plural": "StockCheckProducts",
            },
        ),
        migrations.AlterField(
            model_name="productbay",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stock_check.stockcheckproduct",
            ),
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
