# Generated by Django 2.0.5 on 2018-05-29 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("stock_check", "0005_auto_20180514_0933")]

    operations = [
        migrations.RemoveField(model_name="bay", name="warehouse"),
        migrations.AlterField(
            model_name="product",
            name="bays",
            field=models.ManyToManyField(
                through="stock_check.ProductBay", to="inventory.Bay"
            ),
        ),
        migrations.AlterField(
            model_name="productbay",
            name="bay",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.Bay"
            ),
        ),
        migrations.DeleteModel(name="Bay"),
        migrations.DeleteModel(name="Warehouse"),
    ]
