# Generated by Django 2.1.7 on 2019-02-26 11:48

from django.db import migrations


def clear_product_bays(apps, schema_editor):
    """Delete all ProductBay instances."""
    ProductBay = apps.get_model("stock_check", "ProductBay")
    ProductBay.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [("stock_check", "0006_auto_20180529_1010")]

    operations = [migrations.RunPython(clear_product_bays)]
