# Generated by Django 2.1.7 on 2019-02-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("stock_check", "0007_clear_product_bays")]

    operations = [
        migrations.RemoveField(model_name="product", name="bays"),
        migrations.RemoveField(model_name="productbay", name="bay"),
    ]
